iotbx/command_line/merging_statistics.py
iotbx/merging_statistics.py
iotbx/regression/tst_merging_statistics.py
scitbx/math/__init__.py

Let xia2 calculate merging statistics using cctbx. Increase speed of sorting flex tables.

Dials 1.1.1

---

.gitattributes
dxtbx/data/detectors.lib
dxtbx/format/FormatCBFMiniEigerPF.py
dxtbx/format/FormatPilatusHelpers.py
dxtbx/serialize/xds.py

Dials 1.1.2

---

boost_adaptbx/rational_ext.cpp
cctbx/xray/conversions.h
chiltbx/str.h
gltbx/wx_viewer.py
libtbx/SConscript

fix Mac OS X build, colors for Windows RLV

Dials 1.1.3

---

dxtbx/format/FormatCBFCspad.py
dxtbx/format/FormatCBFFullPilatus.py
dxtbx/format/FormatCBFFullPilatusCdTe300K.py
dxtbx/format/FormatCBFMiniEigerPF.py
dxtbx/format/FormatCBFMiniPilatus.py
dxtbx/format/FormatCBFMiniPilatusDLS6MSN100.py
dxtbx/tests/model/tst_detector.py
dxtbx/tests/model/tst_pixel_to_millimeter.py

Dials 1.1.4

---

rstbx/slip_viewer/tile_generation.py

Partially reverts e6d11ba698a38cdb0fc86e120e7cdf75d2292456.

Use center of mass for calculation of tile transformations

---

dxtbx/format/FormatHDF5Nexus.py
dxtbx/format/FormatHDFEigerNearlyNexus.py
dxtbx/format/FormatNexus.py
dxtbx/format/nexus.py

Code changes to support multi-panel full NeXus files
Code developed against CSPAD CBF data converted to NeXus using cbf2nexus, part of cbflib.

Cspad nexus

---

xfel/command_line/xtc_process.py

Read smd data in stripping mode. Compatible with process_percent. Get rid of << symbol.

Add smd-read feature.

---

libtbx/test_utils/parallel.py

With the current test runner, tests that are skipped and don't run show as "`[OK]`" - this can be extremely misleading because running the tests without e.g. all the regression data configured will state that tests have all passed, when none of them actually ran. Also confusingly, when `phenix_regression` is configured some of these (but perhaps not all) are classified instead as warnings - which may mask actual important warning information.
This patch alters the test runner to recognise skips the same way as it does for the JUnit XML output.
This means that it works by looking for the case insensitive word 'skip' in the output. Consequently, output that's a multi-test script consisting of passes/skips are classified as skipped - under the reasoning that it's better to know when tests …

Add recognition of skipped tests to run_tests_parallel

---

xfel/command_line/xtc_process.py

Handling real-time events with the new psana rax mode.

Client-server in psana rax mode

---

dxtbx/boost_python/imageset_ext.cc
dxtbx/imageset.h
dxtbx/model/beam.h
dxtbx/model/boost_python/beam.cc
dxtbx/model/boost_python/crystal.cc
dxtbx/model/boost_python/experiment.cc
dxtbx/model/boost_python/experiment_list.cc
dxtbx/model/boost_python/to_from_dict.h
dxtbx/model/crystal.h
dxtbx/model/experiment.h
dxtbx/model/experiment_list.h

Refactor Crystal and Beam models to be polymorphic using base classes with virtual methods.

Polymorphic crystal and beam

---

xfel/command_line/cxi_merge.py
xfel/command_line/print_pickle.py
xfel/cxi/merging_database.py
xfel/cxi/merging_database_fs.py
xfel/cxi/util.py

Safe cherry-picked merged from sept_sprint, regarding stills-merging.
Adds support for tar globs & better MySQL support.

Merge staging

---

xfel/command_line/cxi_merge.py

Changes to cxi_merge.py to selectively filter unit cells.

Updated cxi_merge.py for cell rejection

---

xfel/merging/command_line/dev_cxi_merge.py
xfel/merging/command_line/dev_cxi_merge_refltable.py
xfel/merging/command_line/dev_cxi_mpi_merge_refltable.py
xfel/merging/command_line/dev_mpi_cluster_two_merge.py

Uses mixin classes to create an mpi version of the reflection table merger.  Concurrent updates to other dev programs to support this.

Add dev.cxi.mpi_merge_refltable

---

dxtbx/model/beam.h
dxtbx/model/boost_python/beam.cc
dxtbx/tests/model/experiment/tst_experiment_list.py
dxtbx/tests/model/tst_beam.py
dxtbx/tests/serialize/tst_serialize.py

This branch contains changes to dxtbx to support scan-varying beam vector s0. These changes add rather than alter functionality and are expected to be safe. However, the details of serialisation in particular are tricky, so I request review from @jmp1985 to check I haven't missed anything.

Scan varying beam

---

dxtbx/model/profile.py
dxtbx/tests/model/tst_profile.py

counterpart to dials/dials#532

Removing dials extensions

---

boost_adaptbx/meta_ext.cpp
boost_adaptbx/python_streambuf.h
cctbx/maptbx/boost_python/pymol_interface.cpp
gltbx/pointer_args_bpl.h
iotbx/pdb/hierarchy_atom_bpl.cpp
iotbx/pdb/hierarchy_bpl.h
iotbx/pdb/hierarchy_ext.cpp
iotbx/pdb/input_bpl.cpp
iotbx/pdb/write_utils_bpl.h
libtbx/__init__.py
libtbx/command_line/run_tests_parallel.py
libtbx/introspection.py
libtbx/phil/__init__.py
libtbx/phil/tokenizer.py
libtbx/test_utils/__init__.py
libtbx/test_utils/parallel.py
scitbx/array_family/boost_python/byte_str.h
scitbx/array_family/boost_python/flex_pickle_double_buffered.h
scitbx/array_family/boost_python/flex_pickle_single_buffered.h
scitbx/array_family/boost_python/flex_std_string.cpp
scitbx/array_family/boost_python/numpy_bridge.cpp
scitbx/boost_python/container_conversions.h
scitbx/boost_python/cstringio_utils.h

cctbx should compile using python3. Tested on Linux.

cctbx python3 c++ compilation fixes

---

xfel/command_line/brehm_diederichs.py
xfel/command_line/cxi_merge.py

Several patches that fix bugs found by @MVAppleby

Cxi.merge patches

---

xfel/cftbx/detector/cspad_cbf_tbx.py
xfel/command_line/xtc_process.py

An attempt to make psana2 detector interface compatible with psana1

Update psana2 detector interface.

---

libtbx/auto_build/package_defs.py

Just dependency updates.
Resolves #192 as a side effect.

Update HDF5 and h5py

---

xfel/command_line/cxi_mpi_submit.py
xfel/command_line/h5_average.py
xfel/command_line/xfel_process.py
xfel/ui/components/submission_tracker.py
xfel/ui/components/xfel_gui_dialogs.py
xfel/ui/components/xfel_gui_init.py
xfel/ui/db/__init__.py
xfel/ui/db/cfgs/submit_xfel_process.phil
xfel/ui/db/frame_logging.py
xfel/ui/db/job.py
xfel/ui/db/stats.py
xfel/ui/db/xfel_db.py
xfel/util/mp.py

This pull requests brings in recent work to enable using the XFEL GUI at SACLA under the PBS queueing system.  As a nice side effect, the GUI now can be run standalone at other facilities on h5 files or directories full of images.
Includes commits from @asmit3 and @idyoung.  Thanks.

Standalone XFEL gui

---

dxtbx/format/FormatMultiImage.py
dxtbx/format/FormatNexus.py
dxtbx/format/nexus.py
xfel/euxfel/agipd_cxigeom2nexus.py

Progress on EuXFEL work:
- Handle 4 dimensional data
- Derive FormatNexusStill from FormatMultiImageLazy
- Handle different source data formats from EuXFEL

Nexus edits for EuXFEL

---

dxtbx/format/nexus.py
xfel/euxfel/agipd_cxigeom2nexus.py

This is to match spec. Fixes #305.
See http://download.nexusformat.org/sphinx/classes/applications/NXmx.html

Reverse the order NeXus reads in data_origin and data_size

---

dxtbx/format/FormatHDF5EigerNearlyNexus.py
dxtbx/format/FormatNexus.py
dxtbx/format/nexus.py

Now that nexusformat/definitions#654 is merged, we can add the multi-image mask to the nexus format class.

Support multi-image masks in nexus. Resolves #308.

---

xfel/command_line/recompute_mosaicity.py
xfel/command_line/xtc_process.py
xfel/small_cell/small_cell.py

Synch cctbx.xfel with dials index refactoring dials/dials#805

synch cctbx.xfel with dials index refactoring PR

---

iotbx/detectors/mar.py

* use context managers for file operations
* campsite tidying

Fix MAR format for Python 3

---

iotbx/detectors/npy.py

Fix npy detector format for Python 3

---

libtbx/SConscript
simtbx/nanoBragg/cuda_compatibility.h
simtbx/nanoBragg/nanoBragg.cpp
simtbx/nanoBragg/nanoBragg.h
simtbx/nanoBragg/nanoBraggCUDA.cu
simtbx/nanoBragg/nanoBragg_cuda.cpp
simtbx/nanoBragg/nanoBragg_ext.cpp

Request permission to merge nanoBragg cuda code written by @jmholton  and Giles Mullen into master. In addition to adding the cuda code, this allows compilation for multiple architectures and a way to set device Id at runtime from a nanoBragg instance (for working on multi-GPU nodes). Does the cuda code need a copyright ?

Gpu to master less

---

rstbx/indexing_api/tools.py

fixes 39 DIALS Python 3 tests as part of dials/dials#843
resolves #359

Fix rstbx/indexing_api/tools for Python3

---

iotbx/mtz/object.h

On deleting multiple entries create a new array and copy all remaining
elements into the new array in O(n).
This replaces the previous implementation where each element is removed
individually by shifting the remainder of the array one place forward
in O(n²).
Fixes #320

Make mtz.object.delete_reflections() efficient

---

iota/__init__.py
iota/components/iota_base.py
iota/components/iota_threads.py
iota/components/iota_ui_frames.py
iota/doc/NOTES.txt

This branch has the following changes: 
bugfixes to UI
- monitor mode bug(s) related to HDF5 upgrades
- fixed image viewer launch from processing tab

bugfixes to UI

---

mmtbx/regression/tls/tst_tls_optimise_amplitudes.py
mmtbx/tls/optimise_amplitudes.cpp
mmtbx/tls/optimise_amplitudes.h
mmtbx/tls/optimise_amplitudes.py
mmtbx/tls/optimise_amplitudes_ext.cpp

-- added lasso and ridge regression penalties
-- added/expanded tests for new functions
-- fix white-space/indentation to be consistent 2-space throughout
-- rename variable names for clarity
all tests run on linux cleanly
libtbx.find_clutter runs cleanly
libtbx.find_unused_imports_crude runs cleanly
should be python3-compatible but not tested

updates to tls/uij magnitude optimisation

---

cctbx/sgtbx/__init__.py
cctbx/sgtbx/boost_python/tst_sgtbx.py

```
from cctbx import sgtbx
repr(sgtbx.space_group_info("P 1"))
'sgtbx.space_group_info(symbol="P 1")'
repr(sgtbx.space_group_info("I2"))
'sgtbx.space_group_info(symbol="I 1 2 1")'
```

Add __repr__ to sgtbx.space_group_info

---

scitbx/array_family/boost_python/tst_flex.py
scitbx/array_family/flex.py

Alternate version of #381 with test in tst_flex.py.  Fixes #380 and resolves #381.
Thanks Matt!

Add flex.vec3_double().as_numpy_array()

---

xfel/euxfel/agipd_cxigeom2nexus.py

`py3`-compatibility changes in `agipd_cxigeom2nexus.py`
@phyy-nx please have a look

EuXFEL AGIPD: py3-compatibility

---

smtbx/command_line/anom_refine.py
smtbx/regression/tst_commandline_anomrefine.py

This just adds esd's to the output of smtbx.anom_refine. I don't know why there would be any objection but I will leave this PR here for a couple days to be sure. After that @bkpoon I'm happy to merge it in myself if it's ok with you.

Output esd's of fp and fdp in smtbx.anom_refine

---

crys3d/command_line/multiplicity_viewer.py
crys3d/hklview/frames.py
crys3d/hklview/view_2d.py
gltbx/pointer_args_bpl.h
wxtbx/phil_controls/text_base.py

* wx.TaskBarIcon -> wx.adv.TaskBarIcon
* wx.EmptyIcon -> wx.Icon
* wx.EmptyBitmap -> wx.Bitmap
* wx.PyPanel -> wx.Panel
* wx.PyValidator -> wx.Validator
* AddLabelTool -> AddTool
* AppendItem -> Append
* wx.OPEN -> wx.FD_OPEN
* wx.SAVE -> wx.FD_SAVE

wxPython4 fixes for multiplicity viewer

---

xfel/command_line/experiment_residuals.py

experiment residuals commit

---

mmtbx/atomic_environment_vectors/__init__.py

Fixing some bugs and adding some comments.

Bob's Change

---

mmtbx/scaling/matthews.py

PR in case anything depends on existing text output

Trivial fix: typo in numer

---

cctbx/__init__.py

Update cctbx's python copy of factor_kev_angstrom constant

---

xfel/merging/application/model/crystal_model.py

As discussed with @phyy-nx and @nksauter. I'll go ahead and merge this if the tests pass.

Support cif format for xfel scaling model

---

iotbx/file_reader.py
iotbx/reflection_file_reader.py

from looking at the [most recent Azure output.](https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=10568&view=logs&jobId=468d389b-3100-57be-fd90-3b340e8025d2&j=468d389b-3100-57be-fd90-3b340e8025d2&t=003de81b-4ff1-5182-bb53-ce89da252755)

more iotbx ResourceWarnings

---

xfel/conda_envs/README.md
xfel/conda_envs/psana_lcls_environment.yml
xfel/conda_envs/test_psana_lcls.sh

Couple of missing instructions, useful for the non-expert.

Update XFEL build instructions

---

simtbx/gpu/simulation.cuh

This fixes some unpredictable crashes in experimental LS49 code

set Fhkl to 0 if the pixel is outside hkl limits

---

.azure-pipelines/xfel/download-source.yml
.azure-pipelines/xfel/unix-conda-build.yml
xfel/merging/application/lunus/factory.py
xfel/merging/application/lunus/lunus.py
xfel/merging/application/phil/phil.py

Add a worker to cctbx.xfel.merge to run [Lunus](https://github.com/lanl/lunus.git) on integrated images using MPI.  Will be used for analysis of diffuse scattering from protein crystals. Includes test added to xfel_regression and the XFEL Azure CI.
Co-authored-by: Mike Wall <mewall@lanl.gov>

Lunus merging worker

---

mmtbx/refinement/ensemble_refinement/__init__.py

Updated version of ensemble refinement to include den restraints and echt b-factor model to accompany paper submitted to Acta D.  Tested with phenix-1.19.2-4158.  Issues with previous pull request (https://github.com/cctbx/cctbx_project/pull/528#issuecomment-697779661) fixed.

Update ensemble refinement

---

cctbx/geometry_restraints/auto_linking_types.py
cctbx/geometry_restraints/linking_class.py
iotbx/pdb/__init__.py
iotbx/pdb/atom_name_interpretation.py
mmtbx/model/model.py
mmtbx/monomer_library/pdb_interpretation.py

A way to get the type_energy out of the interpretation.

start of type_energies for all atoms

---

simtbx/nanoBragg/nanoBragg.cpp
simtbx/nanoBragg/nanoBragg_ext.cpp

Fix windows build problem related to isnan

---

simtbx/SConscript
simtbx/run_tests.py

currently diffBragg should be build with c++11 enabled

checks for cxx11 before diffBragging

---

libtbx/SConscript
simtbx/kokkos/SConscript

The sconscript requires a few changes to build on perlmutter

Adapt libtbx/Sconscript for perlmutter

---

simtbx/command_line/hopper.py
simtbx/diffBragg/hopper_utils.py
simtbx/diffBragg/phil.py
simtbx/diffBragg/src/diffBraggCUDA.cu
simtbx/diffBragg/src/diffBragg_cpu_kernel.cpp
simtbx/diffBragg/src/diffBragg_gpu_kernel.cu
simtbx/diffBragg/src/diffBragg_gpu_kernel.h
simtbx/diffBragg/tests/tst_diffBragg_diffuse_properties.py
simtbx/diffBragg/tests/tst_diffBragg_hopper_refine.py

Diff bragg diffuse

---

simtbx/command_line/hopper.py
simtbx/command_line/hopper_process.py
simtbx/diffBragg/hopper_utils.py
simtbx/diffBragg/phil.py
simtbx/diffBragg/src/diffBragg_cpu_kernel.cpp
simtbx/diffBragg/src/diffBragg_ext.cpp
simtbx/diffBragg/src/diffBragg_gpu_kernel.cu
simtbx/diffBragg/src/util.h
simtbx/diffBragg/tests/tst_diffBragg_diffuse_properties.py
simtbx/modeling/forward_models.py
simtbx/modeling/predictions.py

replaces methods in dials.stills_process with diffBragg ones

Diff bragg prediction

---

mmtbx/programs/probe2.py
mmtbx/programs/reduce2.py
mmtbx/reduce/Movers.py
mmtbx/reduce/Optimizers.py

Does not add flip Movers in Reduce2 by default (matches original Reduce).
Tries double Hydrogen removal in Histidine with a penalty (matches original Reduce).
License additions to source files.

Molprobity2 debug

---

iotbx/pdb/hierarchy.cpp
mmtbx/probe/AtomTypes.py
mmtbx/probe/Helpers.py
mmtbx/programs/probe2.py
mmtbx/programs/reduce2.py
mmtbx/reduce/InteractionGraph.py
mmtbx/reduce/Optimizers.py

Features, bug fixes, and unit test for mmtbx/probe and mmtbx/reduce.

Molprobity2 improvements

---

xfel/pal/jf4m_geom2nexus.py

Added the dtype='i' to h5py.VirtualLayout. for generating master.h5 for data from PAL-XFEL.

Added the dtype='f' to h5py.VirtualLayout

---

simtbx/__init__.py
simtbx/gpu/detector.cu
simtbx/gpu/detector.h
simtbx/gpu/gpu_ext.cpp
simtbx/gpu/simulation.cu
simtbx/gpu/simulation.h
simtbx/gpu/structure_factors.h
simtbx/gpu/tst_exafel_api.py
simtbx/gpu/tst_gpu_multisource_background.py
simtbx/kokkos/detector.cpp
simtbx/kokkos/detector.h
simtbx/kokkos/kokkos_ext.cpp
simtbx/kokkos/simulation.cpp
simtbx/kokkos/simulation.h
simtbx/kokkos/simulation_kernels.h
simtbx/kokkos/structure_factors.h
simtbx/kokkos/tst_kokkos_lib.py
simtbx/modeling/forward_models.py

Exascale API is polymorphic
Same Python script implements either CUDA or Kokkos

Kokkos incoming

---

mmtbx/probe/CompareOriginalAndNewProbeAtomInfo.py
mmtbx/probe/Helpers.py
mmtbx/probe/Scoring.cpp
mmtbx/probe/Scoring.h
mmtbx/probe/boost_python/probe_bpl.cpp
mmtbx/programs/probe2.py
mmtbx/programs/reduce2.py
mmtbx/reduce/Optimizers.py

Adds Probe2 vs. Probe regression test program along with command-line options for dumping atom type and radius information to be compared.
Marks Nitrogens in HET groups that have no bound Hydrogens as acceptors, bringing the Probe and Probe2 scores very close together for 4fenH.
Other features and bug fixes for Probe2 and Reduce2.

Molprobity2 improvements2

---

simtbx/command_line/hopper.py
simtbx/command_line/hopper_process.py
simtbx/command_line/stage_two.py
simtbx/diffBragg/ensemble_refine_launcher.py
simtbx/diffBragg/hopper_utils.py
simtbx/diffBragg/phil.py
simtbx/diffBragg/refiners/stage_two_refiner.py
simtbx/diffBragg/src/diffBraggCUDA.cu
simtbx/diffBragg/src/diffBragg_cpu_kernel.cpp
simtbx/diffBragg/src/diffBragg_ext.cpp
simtbx/diffBragg/src/diffBragg_gpu_kernel.cu
simtbx/diffBragg/src/diffBragg_gpu_kernel.h
simtbx/diffBragg/src/util.h
simtbx/diffBragg/stage_two_utils.py
simtbx/diffBragg/utils.py
simtbx/modeling/forward_models.py
simtbx/modeling/predictions.py

Includes updates made to diffBragg while getting it to work on tethrene small molecule XFEL data

Small mol updates

---

.azure-pipelines/unix-conda-build.yml
libtbx/auto_build/bootstrap.py

Fix for #704 and [alcc-recipes #7](https://github.com/JBlaschke/alcc-recipes/issues/7)

Bump Eigen to 3.4.0

---

xfel/util/kapton_2019_correction_frame_frame_plugin.py

Most recent commit includes to logic to fix inability to draw proper max absorption edge by replacing the 'map_coords' function inside DrawEdgeMax with a new class method, '_map_coords'. The new class method was based on a different sub-function 'map_coords' that was located inside the UpdateAbsorption function. For consistency, the UpdateAbsorption function was modified to use the '_map_coords' class method.

Added optional plugin for Kapton absorption for image viewer

---

scitbx/array_family/boost_python/flex_vec2_double.cpp
scitbx/array_family/boost_python/tst_flex.py

Add functions for each_normalize() and rotate_around_origin(),
especially useful for processing pixelwise image data.

Updated interface for vec2_double.

---

simtbx/kokkos/SConscript

Make kokkos configuration more transparent

Print kokkos configuration during build process

---

simtbx/command_line/hopper.py
simtbx/diffBragg/ensemble_refine_launcher.py
simtbx/diffBragg/hopper_utils.py
simtbx/diffBragg/phil.py
simtbx/diffBragg/refiners/parameters.py
simtbx/diffBragg/src/diffBraggCUDA.cu
simtbx/diffBragg/src/diffBraggCUDA.h
simtbx/diffBragg/src/diffBragg_gpu_kernel.cu
simtbx/diffBragg/src/diffBragg_gpu_kernel.h
simtbx/diffBragg/stage_two_utils.py
simtbx/diffBragg/tests/tst_diffBragg_structure_factors.py
simtbx/diffBragg/utils.py
simtbx/modeling/forward_models.py
simtbx/nanoBragg/__init__.py

lots of updates to (mostly) diffBragg

Simtbx updates

---

simtbx/command_line/geometry_refiner.py
simtbx/diffBragg/hopper_utils.py
simtbx/diffBragg/phil.py
simtbx/diffBragg/refiners/parameters.py
simtbx/diffBragg/utils.py
simtbx/modeling/predictions.py

mostly updates revolving around per-spot refinement

Diff bragg updates

---

simtbx/diffBragg/utils.py
simtbx/nanoBragg/anisotropic_mosaicity.py
simtbx/nanoBragg/nanoBragg_crystal.py
simtbx/nanoBragg/sim_data.py

np.bool and from collections import Iterable
will soon throw errors

guards against deprecation errors

---

xfel/ui/components/xfel_gui_dialogs.py

no more accidentally submitting 500 jobs

cctbx.xfel: default rungroup only contains 1 run

---

xfel/small_cell/command_line/small_cell_index.py
xfel/small_cell/small_cell.py

small_cell: limit calls to bronk2

---

mmtbx/probe/Helpers.py
mmtbx/probe/README.md
mmtbx/programs/probe2.py
mmtbx/reduce/Movers.py
mmtbx/reduce/Optimizers.py

Version 1.0.0 of Probe2 passes regression tests against Probe.  It is either equivalent or better on the cases we have tested.

Molprobity2 debug3

---

mmtbx/domains_from_pae.py

I've updated the parser to work with pkl files made in alphafold monomer_ptm/multimer runs and to work with the newly updated PAE format in the alphafold database v3.

Updated parse_pae_file function

---

mmtbx/probe/AtomTypes.py
mmtbx/probe/Helpers.py
mmtbx/probe/SpatialQuery.cpp
mmtbx/probe/SpatialQuery.h
mmtbx/programs/probe2.py
mmtbx/programs/reduce2.py
mmtbx/reduce/Movers.py
mmtbx/reduce/Optimizers.py

Specifies default file name for probe2 output.
Added short descriptions for probe2 Phil parameters.
Changing probe.radius to probe.probe_radius and output.format=standard to output.format=kinemage.
Added neutron-distances flag in reduce2.
Added ignore_lack_of_explicit_hydrogens Phil parameter to probe2.
Cleans up probe2 output.

Molprobity2 debug4 rebase

---

simtbx/kokkos/SConscript
simtbx/kokkos/kokkos_ext.cpp
simtbx/kokkos/kokkos_instance.cpp

Kokkos arcticus update

---

xfel/ui/db/__init__.py
xfel/ui/db/xfel_db.py

This was tested live for 1-2 days at SwissFEL with no apparent problems. Subjectively the GUI was muuuuuch more responsive. @phyy-nx I suspect our test coverage is on the light side here, how do you think we should proceed?

XFEL gui: cache database connections

---

.azure-pipelines/xfel/unix-conda-build.yml
simtbx/kokkos/SConscript

The goal of this PR is to slim down the simtbx/kokkos/SConscript.
Before, the script tries to automagically detect the host system and uses hardcoded configurations.
This PR changes the script to use the env variables "KOKKOS_DEVICES" and "KOKKOS_ARCH" instead, allowing for more flexibility.

Kokkos update scons

---

xfel/swissfel/jf16m_cxigeom2nexus.py

Follow up to cctbx/dxtbx#561, which cuts 2 hierarchy levels off the top of SwissFEL JF16M by collapsing transformations using the equipment_component flag.
This PR removes an extraneous transformation from the NeXus master files at the leaf end, by removing the NXtransformation `/entry/instrument/ELE_D0/transformations/AXIS_D0Q0M0A0` and moving its offset to the fast and slow pixel direction fields of the NXdetector_module `/entry/instrument/ELE_D0/ARRAY_D0Q0M0A0`.

Remove an extra hierarchy level from SwissFEL JF16M NXmx files

---

mmtbx/regression/tst_statistics_output.py
mmtbx/validation/clashscore.py
mmtbx/validation/regression/tst_clashscore.py

proper gap in condensed option. Do not consider 'so' types for consistency. Updated and enhanced tests.

update python part of probe to account for updated output

---

xfel/util/sublattice_helper.py

XFEL cosets: use logger instead of print

---

xfel/conda_envs/psana_environment.yml

Add nxmx to conda dependencies

---

.azure-pipelines/xfel/download-source.yml
xfel/merging/ext.cpp

Use std::shared_ptr instead of boost equivalent

---

xfel/ui/components/xfel_gui_dialogs.py

cctbx.xfel.xtc_process and cxi.xtc_process have both been removed from the dispatcher options in a previous commit. This commit removes code elsewhere that is only reached if one of those dispatchers is selected.

Clean up after removing deprecated dispatcher options.

---

xfel/util/drifter.py

A technical PR since I kinda messed up a few rebases and want to squash-merge all this merge onto a copy of master. Do not mind it!

Xfel drift plotter

---

wxtbx/metallicbutton.py

- DrawBitmap requires x,y to be integers
- GetLabel rquires x,y to be integers

fixes to MetallicButton to address wxPython 4.2.0 changes

---

iotbx/pdb/atom_selection.cpp
iotbx/pdb/hierarchy.cpp
iotbx/pdb/hierarchy.h
iotbx/pdb/hierarchy_atom_bpl.cpp
iotbx/pdb/hierarchy_bpl.h
iotbx/pdb/hierarchy_ext.cpp
iotbx/pdb/hierarchy_select.cpp
iotbx/pdb/hierarchy_write.cpp
iotbx/pdb/mmcif.py
iotbx/pdb/overall_counts.cpp
iotbx/pdb/small_str.h
iotbx/pdb/tst_hierarchy.py
iotbx/pdb/tst_mmcif_hierarchy.py

Changing type of residue name from str3 to std::string in preparation for longer residue names

Resname to std string

---

simtbx/command_line/hopper.py
simtbx/command_line/integrate.py
simtbx/diffBragg/hopper_io.py
simtbx/diffBragg/hopper_utils.py
simtbx/diffBragg/phil.py
simtbx/diffBragg/refiners/stage_two_refiner.py
simtbx/diffBragg/stage_two_utils.py
simtbx/diffBragg/utils.py
simtbx/nanoBragg/utils.py

Some minor updates needed to get the stage 2 results from the diffBragg paper working again. Results can be generated using instructions in the README here: 
https://github.com/dermen/cxid9114

Checking stage2

---

mmtbx/domains_from_pae.py

Please see https://github.com/igraph/python-igraph/issues/699 for why this is necessary.

change python-igraph to igraph in error message

---

xfel/merging/application/statistics/intensity_resolution_statistics_cxi.py

Bug arises from cd5a215da6aa3fcdba4c86f1339133d9f056b573

AttributeError bugfix in CCiso statistics.

---

.azure-pipelines/xfel/download-source.yml
.azure-pipelines/xfel/unix-conda-build.yml

Try executing cmake in the kokkos source dir instead of in the build dir

Debug kokkos cmake build error

---

simtbx/diffBragg/src/diffBragg.cpp
simtbx/diffBragg/src/diffBragg.h
simtbx/diffBragg/src/diffBraggCUDA.cu
simtbx/diffBragg/src/diffBraggKOKKOS.cpp
simtbx/diffBragg/src/diffBragg_cpu_kernel.cpp
simtbx/diffBragg/src/diffBragg_ext.cpp
simtbx/diffBragg/src/diffBragg_gpu_kernel.cu
simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp
simtbx/modeling/forward_models.py

this shouldnt affect any of the exafel workflows, and changes no defaults.. Simply adds the option to store the average hkl visited by the kernel in each pixel (important for Laue work currently with Hekstra lab)

adds option to store average wavelength per pixel

---

gltbx/gl.py
gltbx/gl_managed.py
gltbx/glu.py

Migrate `gltbx` to use `pyopengl`

---

fable/docker/Dockerfile
fable/docker/README.md

Dockerfile to build and run fable
described in README

Added fable docker

---

fable/fem/intrinsics.hpp

these are in intrinsics.py but not intrinsics.hpp

add some missing functions to intrinsics.hpp

---

libtbx/auto_build/bootstrap.py
libtbx/auto_build/install_conda.py

Integrate molstar installation into bootstrap script

Bootstrap molstar adaptbx

---

xfel/merging/application/filter/reflection_filter.py

Handle ranks with no reflections

xfel.merge: patch for isolation forest filter

---

mmtbx/probe/AtomTypes.py
mmtbx/probe/Helpers.py
mmtbx/programs/probe2.py
mmtbx/programs/reduce2.py
mmtbx/reduce/Optimizers.py

Fix for issue https://github.com/cctbx/cctbx_project/issues/1062 where the Histidine ring Nitrogens were not being marked as acceptors in Probe2 or Reduce2.

Histidine h bonds fix
