cctbx/cctbx_project

libtbx/test_utils/parallel.py
Hi Nigel,
Do we really need these
```ERROR BEGIN ERROR BEGIN ERROR BEGIN ERROR BEGIN ERROR BEGIN
...
ERROR -END- ERROR -END- ERROR -END- ERROR -END- ERROR -END-```
blocks in the ```libtbx.run_tests_parallel``` output by default?
I find that when I run it manually they obscure the relevant OK/FAIL/WARNING overview and are generally not helpful because in 99% of the time they are false positives anyway. The similar block for the exit code is redundant because that is displayed in any case.
May I suggest removing this output by default?
With this patch you can run ```libtbx.run_tests_parallel verbosity=2``` to switch it back on, but it is no longer printed for everyone.
(In case you use these markers to scrape the ```libtbx.run_tests_parallel``` output with another script - have a look at …
=> Disable libtbx.run_tests_parallel 'ERROR BEGIN' etc output by default 

dxtbx/SConscript
Add the the library folder in anaconda installations to env_etc.dxtbx_lib_paths in order to find libhdf5. This makes it possible to compile cctbx in anaconda.
=> modify dxtbx_lib_paths for anaconda

cbflib_adaptbx/detectors/cbf_byte_offset_optimized.cpp
Move cbf.h outside of the extern C block. This make cctbx compile if the hdf5 library is build with c++ bindings.
related to :
https://github.com/yayahjb/cbflib/pull/4
=> move cbf.h outside extern C

dxtbx/format/FormatHDFEigerNearlyNexus.py, dxtbx/format/nexus.py, iotbx/detectors/eiger.py
1) Swap Z values in Eiger data using NearlyNexus.  This is to align stored data with documented coordinate systems.  The Eiger system should match the NeXus system, but the Eiger stores negative Z values instead of positive.
2) Revert 'world inversion' where the beam vector, origin, fast and slow vectors were all inverted.  Instead, add a change of basis to nexus.py that converts between the NeXus and IUCr systems.  Essentialy swaps sign of X and Z directions.
=> Putative coordinate fixes for Eiger and NeXus data

scitbx/array_family/boost_python/flex_bool.cpp
Using this test script:
```
from scitbx.array_family import flex
g = flex.grid((2527, 2463))
import time
t0 = time.time()
N = 100
a = flex.random_bool(size=g.size_1d(), threshold=0.5)
b = flex.random_bool(size=g.size_1d(), threshold=0.5)
t0 = time.time()
for i in range(N):
a &= b
t1 = time.time()
print "scitbx: a &= b"
print "Total time:", t1 - t0
print "Per call:", (t1 - t0)/N
a = flex.random_bool(size=g.size_1d(), threshold=0.5)
b = flex.random_bool(size=g.size_1d(), threshold=0.5)
t0 = time.time()
for i in range(N):
c = (a & b)
t1 = time.time()
print "scitbx: c = (a & b)"
print "Total time:", t1 - t0
print "Per call:", (t1 - t0)/N
a = flex.random_bool(size=g.size_1d(), threshold=0.5).as_numpy_array()
b = flex.random_bool(size=g.size_1d(), threshold=0.5).as_numpy_array()
t0 = …
```
=> this appears to be ~100x faster than the existing code

dxtbx/model/__init__.py, dxtbx/model/boost_python/crystal.cc, dxtbx/model/crystal.h, dxtbx/model/crystal.py, dxtbx/serialize/xds.py, dxtbx/tests/model/tst_crystal_model.py, dxtbx/tests/serialize/tst_crystal_model_serialize.py, prime/command_line/frame_extractor_by_scan.py, rstbx/apps/stills/dials_refinement_preceding_integration.py, xfel/command_line/frame_extractor.py, xfel/command_line/frame_unpickler.py, xfel/ui/db/experiment.py
Remove mosaicity from Crystal model. Add two classes that derive from Crystal: MosaicCrystalKabsch2010 (single mosaic parameter expressed as an angle) and MosaicCrystalSauter2014 (two mosaic parameters, domain size and angle).
=> New dxtbx models

dxtbx/format/Registry.py
Changes to Registry.py to allow dxtbx.print_header to not fail when a string is passed to the command line. For example, if we have a format class called FormatRedHerring.py whose understand method checks if the string passed on the command line is "redherring", the following should not fail.
dxtbx.print_header redherring
Currently, the program fails without searching for all the format classes in dxtbx. This change will be useful for future development where we can pass file identifiers on the command line.
=> changes to Registry.py

xfel/libtbx_config, xfel/merging/command_line/mpi_cluster_merge.py, xfel/merging/command_line/mpi_cluster_two_merge.py, xfel/merging/command_line/mpi_cluster_two_merge_cs.py, xfel/merging/command_line/mpi_merge.py, xfel/merging/command_line/single_node_merge.py, xfel/merging/command_line/worker2.py
New directory structure for command_line scripts related to merging. Added exafel:sept_sprint MPI merging work scripts. 
mpi_merge.py: Use MPI spawn to create new MPI processes, and uses MySQL backend.
mpi_cluster_merge.py: Use MPI (non-spawn) to create new MPI processes, and uses MySQL backend.
mpi_cluster_two_merge.py: Use MPI (non-spawn) to create new MPI processes, and uses FS backend.
mpi_cluster_two_merge_cs.py: Use MPI (non-spawn) to create new MPI processes, and uses FS backend. Work distributed to processes using a client-server model.
=> Added sept_sprint MPI merge files into new command_line directory structure

xfel/command_line/cxi_merge.py, xfel/command_line/cxi_xmerge.py, xfel/merging/command_line/dev_cxi_merge.py, xfel/merging/command_line/dev_cxi_merge_refltable.py, xfel/merging/command_line/mpi_cluster_merge.py, xfel/merging/command_line/mpi_cluster_two_merge.py, xfel/merging/command_line/mpi_cluster_two_merge_cs.py
Two changes to cxi.merge:
Move summation code out of run method into method of the scaling manager
Move plot single reflection histograms to own function
Concurrent changes to dev.cxi.merge
New program dev.cxi.merge_refltable that uses a dials reflection table as the underlying data structure for holding reflections during merging.
=> Add development version of cxi.merge that uses a reflection table

libtbx/__init__.py, libtbx/tst_utils.py
keeping the global namespace clean
Will merge this myself after phenix release.
=> retire unused helper functions numstr7 and real_imag

cctbx/eltbx/distance_based_connectivity.py, libtbx/forward_compatibility.py, scitbx/differential_evolution.py, scitbx/direct_search_simulated_annealing.py, scitbx/math/spe.py, scitbx/math/superpose.py, scitbx/math/tests/tst_bessel.py, scitbx/math/tests/tst_dmatrix.py, scitbx/math/tst_2d_zernike.py, scitbx/math/zernike_align_fft.py, scitbx/regular_grid_on_unit_sphere.py, scitbx/restraints.py, scitbx/stdlib.py, scitbx/tst_smoothing.py
Before this can be merged the following files need to be refactored:
**I'll merge this myself but want to leave it until after the Phenix release is done.**
This was used as a workaround in scitbx because scitbx is shadowing two system library modules (math, random), but relies on being able to import the system libraries as well.
Scitbx could be refactored to remove this stdlib hack entirely, but here I've opted to move the stdlib hack from libtbx/pythonpath into scitbx. This frees up another item from libtbx/pythonpath.
Code was refactored to make explicit whether it refers to python math vs scitbx.math.
=> Retire stdlib top level module.

.gitattributes, dox.sphinx/conf.py, libtbx/command_line/import_all_python.py, libtbx/configure.py, libtbx/pythonpath/deep_thought.py
We hardly knew ye.
Depends on #113. I'll merge this myself but want to leave it until after the Phenix release is done.
Removal of pythonpath should speed up initialization because there are now fewer places to look for imports. Plus nothing remains in there that is in some way required. Plus (nowadays) there should not be a need for such a feature in the first place.
=> Retire pythonpath.

libtbx/auto_build/create_mac_pkg.py
WIll merge this myself after phenix release.
No space to be saved by compressing .pkg installers, but user now has to decompress before installation.
We in fact always unzip the file again before we upload the installer for a release, because the --no-compression flag can't be used via create_installer.py. Avoiding the compression in the first place would save some time.
=> Do not compress MacOS .pkg installers

libtbx/env_config.py
Another solution for b46e27a is to set PYTHONPATH to include python lib for python used to create the virtualenv (__future__.py is not present in virtualenv's lib/python27).
=> Virtualenv issues

libtbx/env_config.py
By default boost threads is disabled. New features in DIALS require boost threads to be built. Therefore, it would be desirable to have this enabled by default.
Are there are reasons why this can't be done? I don't intend to merge this before the next Phenix release (or probably until the New year anyway).
=> Enable boost threads by default

xfel/command_line/xtc_process.py
Fixes a bug where enumerating multiple runs causes events to be processed under the wrong run, because `ds.events()` returns all the events, instead of the events for a specific run.
=> Fix xtc_process when reading multiple runs

dxtbx/model/boost_python/scan.cc, dxtbx/model/scan.h, dxtbx/model/scan.py, dxtbx/tests/model/tst_scan_data.py, dxtbx/tests/serialize/tst_serialize.py
Add a batch_offset attribute to the dxtbx scan model.
This is to allow tracking/handling of unique batch numbers for multi-crystal datasets when interacting with CCP4 programs such as POINTLESS and AIMLESS.
Batch numbers are implemented as the image number plus an offset (default is zero).
See also:
http://www.ccp4.ac.uk/html/mtzformat.html
http://www.ccp4.ac.uk/html/aimless.html
=> dxtbx: add batch_offset to scan model (in the manner of MTZ batch number column)

libtbx/auto_build/bootstrap.py, libtbx/auto_build/install_base_packages.py, libtbx/auto_build/package_defs.py
This pull request provides an option to install mpi4py during the base step. The flag required is --mpi-build when bootstrap.py is run. In order for the installation to be successful, MPI libraries should be available on your machine. 
If there are no objections within the next 1-2 days to this pull request, I can merge this.
=> Option to install mpi4py during base step

dxtbx/format/FormatHDFEigerNearlyNexus.py, dxtbx/format/nexus.py
Implementing these changes and bringing nexus.py in line with the NeXus format. 
1. Drop _F, _S vectors (including the depends_on list and transformations)
2. Use fast/slow_pixel_direction instead (single entry equal to pixel size) and use module_offset to position these vectors
3. Drop fast_pixel_size
4. Flatten module list
Concurrent changes have been made to dials_regression/test.py to skip testing of LCLS_cspad_nexus master file which is currently inconsistent with the NeXus format. Thus you would need to update dials_regression repository to pass all tests there. 
Work done with @phyy-nx
=> Changes to be consistent with the current nexus format.

prime/command_line/run.py
…and avoid starting another python instance
This seems unnecessary
=> prime: run processing in same address space

prime/command_line/solve_indexing_ambiguity.py
Hi Monarin,
Many thanks for looking into #139 and fixing it. I found that the fix didn't apply to the ambiguity solving step, so this patch applys the same logic from your commit 39adfa20f865e240eb38a54b6a82fd889a59cd51 to solve_indexing_ambiguity.py. Is seems to work for my test case, but thought you should sign it off.
(If you're happy with the patch, can you please click the triangle next to the big green button, and pick "Rebase and merge" to avoid inserting a merge commit? Thanks)
=> prime: Convert pool_map to parallel_map in solve_indexing_ambiguity, #139.

libtbx/phil/__init__.py, libtbx/phil/tst.py
This commit adds the "allow_none" attribute for int/float types (c.f. allow_none_elements for ints/floats).
This would allow a developer to explicitly prevent a user from setting "None" as an allowable value for a given phil parameter. See e.g.:
https://github.com/dials/dials/issues/516
```
$ git diff
diff --git a/algorithms/spot_finding/factory.py b/algorithms/spot_finding/factory.py
index 9420d6e..930fa38 100644
--- a/algorithms/spot_finding/factory.py
+++ b/algorithms/spot_finding/factory.py
@@ -73,7 +73,7 @@ def generate_phil_scope():
max_spot_size = 100
.help = "The maximum number of contiguous pixels for a spot"
"to be accepted by the filtering algorithm."
-        .type = int(value_min=1)
+        .type = int(value_min=1, allow_none=False)
max_separation = 2
.help = "The maximum …
```
=> phil: add allow_none (default=True) attribute for int/float types

dxtbx/format/FormatSMVADSC.py
Depending on how TimePix_SU SMV files are created they may have the line BEAMLINE=TimePix_SU as all upper case or as mixed case. When they are upper case there is sometimes a problem where Dials imports as the wrong SMV format. This should fix it.
=> Make understanding TimePix_SU in header file case insensitive

rstbx/apps/stills/simple_integration.h
Found what looks like a minor bug in RSTBX (via clang warning). Because && has higher precendence than ||, the
code reads:
if ( check_tiles && condA   || condB || condC || candD )
(            &&       )
where it looks like it should read:
if ( check_tiles && ( condA || condB || condC || candD ) )
All tests seem to pass both with & without this change, so it's either not tested or this specific condition isn't tested.
@phyy-nx, I've tagged you as the most likely to look at this because you were the last person to touch this code (admittedly five years ago), but I'm reasonably certain about the change so if you don't have time to look over it I'll merge in a few days.
=> Fix minor operator precedence error in rstbx

simtbx/nanoBragg/brunger_example/run_example.py, simtbx/nanoBragg/nanoBragg.cpp
This branch contains changes to the nanoBragg constructor from dxtbx Detector and Beam models. Previously the code appeared to invert the direction of beam propagation, due to an idiosyncrasy of the Beam class. After fixing that, other definitions had to change (`odet_vector`, `pix0_vector` and point of closest approach). I want to request a review from @jmholton to check I have fixed everything required. 
The direction of the rotation axis is also now set, as `init_defaults` sets this along the beam direction for typical dxtbx models.
The other commit makes a minor change to the brunger_example test script.
=> simTBX dxtbx fixes

xfel/ui/command_line/plot_spotfinder_stats_in_gui.py, xfel/ui/components/spotfinder_plotter.py, xfel/ui/components/spotfinder_scraper.py, xfel/ui/components/xfel_gui_init.py, xfel/util/reflection_length.py
Early version of a tool to get radial components of the lengths of all
spotfinder spots in a strong.pickle file or spotfinder reflection table.
Should be useful for monitoring the LS49 Jungfrau spot shapes.
I have a test ready to commit to xfel_regression.
=> Get radial lengths of all spotfinder spots.

dxtbx/format/FormatMultiImage.py, dxtbx/format/FormatMultiImageJIT.py, dxtbx/format/FormatMultiImageLazy.py, dxtbx/format/FormatXTC.py, dxtbx/format/FormatXTCCspad.py, dxtbx/format/FormatXTCJungfrau.py, dxtbx/format/FormatXTCRayonix.py, dxtbx/imageset.py, dxtbx/tests/tst_imageset.py, xfel/ui/db/frame_logging.py
This pull request introduces and modifies the following features in dxtbx to speed up processing of XTC streams at LCLS - 
1. Add FormatMultiImageJIT (JIT = Just-in-Time) and change FormatXTC to inherit from that class. This allows us to process large XTC streams without loading/setting all the models upfront as is the case with FormatMultiImage. The models are set only when requested by a process. Because of this, a new imageset, ImageSetJIT is necessary since some of the ImageSet features need to be overriden (eg. get_detector etc). The __getitem__ function for ImageSetJIT is also defined since a model (detector,beam etc) for an image needs to be set before further action takes place in imageset.h
Most of the features introduced have little to no duplication of code. The class method …
=> Xtc speedup

dxtbx/command_line/image_average.py, dxtbx/format/FormatCBFMultiTile.py, dxtbx/format/FormatCBFMultiTileHierarchy.py, dxtbx/format/FormatMultiImage.py, dxtbx/format/cbf_writer.py, xfel/cftbx/detector/cspad_cbf_tbx.py
General CBF writer for dxtbx.  Two main changes here:
1. Addition of dxtbx/format/cbf_writer.py.  Given a dxtbx image set, this class can write a general, full CBF including multi-panel and hierarchy support, using code adapted from the XFEL project.
2. Re-write of dxtbx.image_average to use cbf_writer to make full CBFs instead of image pickles.  dxtbx.image_average thus now supports multi-panel, hierarchical images.
I used a branch for these changes to take advantage of TravisCI.  It reports the tests pass.
=> Cbf writer

mmtbx/command_line/rebuild_rotarama_cache.py
```mmtbx.rebuild_rotarama_cache``` is run as part of the bootstrap build stage and is currently the only blocked for Python3 builds. I tried converting the relevant files but doing this would affect too many files, so want to leave this for someone from the mmtbx crew to sort out.
To address the immediate issue this patch catches any exceptions on Python 3 only.
Nothing changes on Python 2
=> Allow rotarama cache rebuild to fail gracefully on Python3

boost_adaptbx/SConscript, scitbx/array_family/boost_python/SConscript
Spin-off from #184.
This addresses a prerequisite issue, namely that ```boost_numpy.dll``` is currently not built on Windows.
It was originally disabled as we thought there was a bug in boost 1.63 (see comments on commit https://github.com/cctbx/cctbx_project/commit/0f26753f6385f8cd88ddd5ce60bc61ff337cdd5c#commitcomment-28701366).
After a couple of hours of investigation I found it was caused by both, a bug in boost 1.63 and a bug in the build instructions. This pull request fixes the latter, but an update to boost >=1.64 is still required to enable boost::numpy on all platforms.
=> Enable compilation of boost::numpy on Windows

xfel/command_line/cxi_merge.py, xfel/command_line/cxi_xmerge.py, xfel/ext.cpp
Adds correct include negatives fix to cxi.xmerge and includes a fix to cxi.merge to not write out reflections with 0 intensity to the .db files.
Disable this commit with include_negatives_fix_27May2018=False.
Co-authored-by: Iris Young <idyoung@lbl.gov>
=> cxi.xmerge include_negatives fix

dxtbx/format/FormatMultiImage.py, dxtbx/imageset.py, dxtbx/tests/test_split_singleimage_datablock.py
Three changes:
1) When constructing an imageset, if check_format=False and single_file_indices not None and not empty, use FormatMultiImage instead of Format to construct the imageset.
2) In FormatMultiImage.get_imageset, if check_format=False, return a Lazy imageset.
3) Mark test as expected to pass
=> Fix split datablocks not being deserialized correctly (#203)

cctbx/web/iotbx_cif_validate.html, fable/doc/index.txt, iotbx/cif/__init__.py, iotbx/examples/iotbx_cif.txt, libtbx/citations.py, libtbx/sphinx/pubmed.py, libtbx/tst_citations.py, prime/postrefine/mod_input.py, sphinx/iotbx/iotbx.cif.rst, ucif/examples/ucif_example.txt, xfel/command_line/smooth_spectrum.py
Hello :-)
The DOI foundation recommends [this new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Yes, a bit ironic that they would change the URL of their service, but it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org). Because the old links with the `dx` subdomain continue to work, there is no urgent need to do anything.
However, I'd hereby like to suggest to follow the new recommendation and update all static DOI links and any code that generates new DOI links.
Cheers!
=> Hyperlink DOIs against preferred resolver

xfel/cftbx/detector/cspad_cbf_tbx.py, xfel/command_line/xtc_process.py
With these changes, the indexing and integration modules can now use psana2 interface to read out detector data (xtc2 format) and calibration files. The selection between the old psana and psana2 is done automatically through version checking.
=> Reading data with psana2

libtbx/auto_build/install_base_packages.py
Fixes #223 crash when using --download-only and pip 18 is installed.
Is not critical. Happy for this to wait until after phenix release.
=> Override pip requirements tracker directory

libtbx/auto_build/bootstrap.py, libtbx/auto_build/create_installer.py, libtbx/auto_build/installer_utils.py, libtbx/auto_build/package_defs.py, libtbx/auto_build/setup_installer.py
A [recent change](https://github.com/cctbx/cctbx_project/commit/bb466f729ad1fb5bee9b89d5227b6d68421f51a5#r30946843) by @bkpoon added this requirement implicitly. This pull request will make that requirement explicit.
Any objections should be filed here.
=> Upgrade bootstrap/installer minimum python requirement to 2.6

libtbx/auto_build/create_installer.py
When generating an installer we automatically generate two
```./xxxxx_env.sh``` and
```./xxxxx_env.csh```
scripts in the top level directory of the installer archive.
If the installer generation is run with ```--installer_script``` then the given script ends up as
```./install```
in the same place.
The user now has two options: They can run the install script or they can source one of the shell scripts.
While the result *may* be the same, we have now identified one case where this led to a runtime bug which was very difficult to track down.
I see two ways of resolving this. Either we add a command line switch to not generate the scripts, or we do not generate the scripts for the installer directory if an installer script is provided. The latter is more
likely to be the expected behaviour. …
=> Installer: Force use of provided script

libtbx/python_code_parsing.py, libtbx/tst_python_code_parsing.py
Hi Luc,
Here are some changes to libtbx/python_code_parsing.py for Python 3 compatibility. Basically, ```__nonzero__``` is replaced by ```__bool__``` in Python 3 and the test has a bunch of ```print``` statements.
The fixes are,
- use ```object``` from ```future.builtins``` that automatically maps ```__nonzero__``` to ```__bool___``` along with other Python 2/3 object mappings. Alternatively, we can just manually map the two if you do not plan on using any of the other standard object attributes.
- replace the ```print``` statements with ```type``` in the test
You can test this by configuring the ```libtbx``` module with Python 3 and running the test file. The test passes in both Python 2 and 3, so the fixes can be merged, but I wanted to double-check with you. Thanks!
=> libtbx: Python 2/3 changes for python_code_parsing

libtbx/command_line/import_all_ext.py
- libtbx.import_all_ext seems to run fine without sorting the list of extension modules
- Remove cmp_so function since cmp is not supported by Python 3
Are there cases where the sort order is still important?
The c8ca6424c2081d73a7433c32533352e19f126dbc commit from @phyy-nx seems to have fixed any dependency issues.
I do have a replacement key function for sorting ready, but if sorting is not necessary, it's probably better to just not sort.
=> libtbx: remove sorting from libtbx.import_all_ext

libtbx/test_utils/__init__.py
It's the same test but without overwriting the Python 2 builtin.
This avoids some confusion and makes  clearer what is actually going on.
=> str change refactor

dxtbx/model/boost_python/scan.cc, dxtbx/model/boost_python/to_from_dict.h, dxtbx/model/scan.h, dxtbx/model/scan.py, dxtbx/tests/model/test_scan_data.py, dxtbx/tests/model/test_to_from_dict.py
The purpose of this addition is to allow different images ranges to be indicated for a sweep containing multiple lattices. This allows separated treatment of experiments which share a scan. It is intended that the map key can be the experiment identifier and the values are scitbx-int-arrays of
image ranges valid for each experiment (in the form [start1, end1, start2, end2, ...] for nonconsecutive ranges). The map is initialised as empty for all constructors.
For example, for a multi-lattice sweep with two lattices (with image range (1,100)), this map could be initially set to {"0", [1, 100], "1", [1, 100] }, then to indicate an excluded range (61 - 80) for experiment "0", it would be updated to {"0" : [1, 60, 81, 100], "1" : [1, 100] }. This can be set/managed by a few helper functions …
=> dxtbx.scan: add a valid_image_ranges map to the scan object

scitbx/array_family/flex.py
The Python collections module has abstract base types for things that can be iterated and things that can be iterated and have a defined length (respectively called Iterables and Sequences).
Here we register the flex array base classes as Iterables and Sequences where appropriate so that flex arrays can now be used in places where the iterability is determined by the Python abstract base class register.
This has no effect on the actual behaviour of flex arrays.
=> Register flex arrays as Sequences and Iterables

mmtbx/geometry_restraints/external.py, mmtbx/model/model.py, mmtbx/refinement/ensemble_refinement/__init__.py, mmtbx/refinement/real_space/individual_sites.py
I left out the `schrodinger.py` and `tst_schrodinger.py` files. 
I updated the ensemble refinement parameter reading, cause, to my understanding, only the default values would be created, and by passing the er_params the schrodinger commandline options would be transferred to the pdb_ip instance.
Also 2 extra lines were added to the individual_sites.py file to shift the structure back to its original position.
=> Implement Schrodinger hooks for refinement programs.

wxtbx/metallicbutton.py, wxtbx/wx4_compatibility.py
Per Nick's request:
- wx4_compatibility has a set of tools to make sure that various controls work with both versions
- metallicbutton has been modified to work with both versions
- so far tested with wxPython 4 on MacOS 10.13 and wxPython4 on RHEL6
=> wxPython 3/4 compatibility

libtbx/auto_build/bootstrap.py
- The optparse module is updated to argparse to more easily handle an optional argument for `--use-conda`
- The base step will optionally install miniconda3 and create an environment
- Or a path to a conda environment can be used
- Or the currently active conda environment can be used
This pull request is more for testing the move from optparse to argparse since `--use-conda` is an optional flag. A consequence of moving to argparse is that the actions and flags should be grouped together and the --use-conda flag should not be before an action since it can have an optional argument. So
`python bootstrap.py hot --builder=cctbx base --nproc=4 --use-conda`
would not work. But,
`python bootstrap.py --builder=cctbx --use-conda --nproc=4 hot update base`
`python bootstrap.py hot update base …
=> Add --use-conda flag to bootstrap.py

libtbx/auto_build/package_defs.py
Before we branch DIALS 1.13 (https://github.com/dials/dials/issues/649) later this month I would like to update the following dependencies to make it easier to support 1.13 for a little bit longer than usual.
This is of particular relevance since plans about a DIALS 2.0 version could make this the final 1.* release.
* cython: update to final bugfix release within same minor version
* future/six: update compatibility packages to latest versions
* h5py: update to most current version
* msgpack: update to most current version before we start using it in earnest
* openssl: LTS update
* procrunner: minor unicode compatibility update
* pytest: update to final 3.* version for improved deprecation warnings
amongst other things
* python 3: maintenance update
=> Dependency updates for DIALS 1.13

xfel/small_cell/small_cell.py
This synchs small_cell indexing with the changes in dials/dials#710. This pull request should only be merged once the dials-2.0 branch has been merged into master (https://github.com/dials/dials/pull/698).
> Move two widely used static functions from the indexing code to flex.reflection_table() to remove the dependency on indexing code in various parts of the codebase.
> 
> * dials.algorithms.indexing.indexer.indexer_base.map_spots_pixel_to_mm_rad() replaced by dials.array_family.flex.reflection_table.centroid_px_to_mm()
> * dials.algorithms.indexing.indexer.indexer_base.map_centroids_to_reciprocal_space() replaced by dials.array_family.flex.reflection_table.map_centroids_to_reciprocal_space()
=> synch small_cell indexing with dials/dials#710

mmtbx/real_space_correlation.py
phenix.real_space_correlation requires a PDB file.
The following change removes the PDB file only restriction.
=> Add support for mmCIF files in phenix.real_space_correlation

scitbx/array_family/flex.py, scitbx/array_family/sort.h
following #288.
Performance impact appears to be, if there is any at all, on the positive side.
=> Use stable sort by default

dxtbx/libtbx_config, dxtbx/libtbx_refresh.py, libtbx/command_line/show_python_dependencies.py, libtbx/env_config.py, libtbx/pkg_utils.py
At the moment python dependency resolution is done and installed at the `libtbx.refresh` stage, via each packages `libtbx_refresh.py`. This can cause problems if packages cannot be installed e.g. on an offline node, or if the global site-packages folder is read-only. 
Having the configuration inside the `libtbx_refresh.py` file means that the only way to tell what's required is by manual inspection or parsing the output of refresh. And, since each package only knows about it's own requirements, leaves the potential of conflicting requirements going unnoticed.
This patch moves the listing of requirements to the libtbx_config configuration file, where the other module dependencies are specified, which means that it can be easily read before running libtbx.refresh - dependencies can be …
=> Define python dependencies in libtbx_config

rstbx/command_line/slip_viewer.py, spotfinder/servers/apache_dials.py, xfel/command_line/cspad_detector_congruence.py, xfel/command_line/cspad_detector_congruence2.py, xfel/command_line/cspad_detector_shifts.py, xfel/command_line/detector_residuals.py, xfel/command_line/experiment_json_to_cbf_def.py, xfel/command_line/xtc_process.py, xfel/small_cell/command_line/small_cell_process.py, xfel/small_cell/small_cell.py, xfel/ui/db/frame_logging.py, xfel/util/reflection_length.py
This is related to the import_experiments branch in dials (https://github.com/dials/dials/pull/613).
I have been trying to remove references to data block in dials in favour of using experiment lists for everything. However, some things in cctbx/xfel and cctbx/iota also rely on dials functions which have now had a change of interface. I thought it would be helpful if I made these changes myself; I tried my best to update things but I don't know what tests to run to ensure my changes are correct. 
@phyy-nx and @alyubimov could you check for me that xfel and iota work using the changes on this branch, or alternatively could you tell me which tests I can run to make sure things are ok? Thanks!
=> Import experiments

scitbx/lstbx/boost_python/normal_equations.cpp, scitbx/lstbx/normal_equations.h, smtbx/refinement/least_squares.py
These changes add an option to choose the method for calculating the A^T W A matrix during add_equation, to enable switching depending on the shape and sparsity of the problem. The default is set to the new behaviour after pull request #295. Setting optimise_for_sparse=False enables one to recover the previous behaviour.
I have verified that I can switch between the old and new behaviour for my use case.
@luc-j-bourhis I would appreciate it if you are able to have a quick check over this and maybe test that everything still works the same for smtbx refinement.
Thanks,
James
=> Lstbx add equations

dxtbx/model/__init__.py, dxtbx/model/experiment_list.py, dxtbx/tests/model/experiment/test_experiment_list.py
Adds load_models as option to the experiment list factory functions.  If False, skip reading the models from the imageset when constructing experiment lists from raw data files.
Closes #307.
This version isn't a general solution like #312 is, but it works.  A concurrent change will need to be made to dials.stills_process.  See dials/dials#744.
=> Add option to delay load models when reading raw data

dxtbx/README.md, libtbx/auto_build/bootstrap.py, libtbx/command_line/install.py, rstbx/SConscript, rstbx/libtbx_config, simtbx/SConscript, spotfinder/SConscript, spotfinder/libtbx_config
Following the decision to move dxtbx to a separate repository and based on the discussion with @bkpoon and @phyy-nx here are the proposed changes and the next steps.
This pull request contains the necessary bits to
* modify bootstrap to check out `dxtbx` from https://github.com/cctbx/dxtbx directly into the modules/ directory
* modify `SConscript` build files of `cctbx_project` modules to include `dxtbx` where required
* modify the [`cctbx_project/dxtbx/README.md` to contain instructions for migrating existing developer setups](https://github.com/cctbx/cctbx_project/blob/4d3948b55ec0785799ecae9578e7da1db1563f87/dxtbx/README.md) using `libtbx.install`, and
* add a corresponding installation routine to `libtbx.install`.
This pull request does not yet remove any files from the …
=> move dxtbx to separate repository

xfel/command_line/cspad_cbf_metrology.py, xfel/command_line/cspad_detector_congruence.py, xfel/command_line/cspad_detector_congruence2.py, xfel/command_line/cspad_detector_shifts.py, xfel/command_line/cspad_detector_statistics.py, xfel/command_line/detector_residuals.py, xfel/command_line/filter_experiments_by_rmsd.py, xfel/command_line/frame_extractor.py, xfel/command_line/frame_unpickler.py, xfel/command_line/recompute_mosaicity.py, xfel/command_line/stills_merge.py, xfel/command_line/striping.py, xfel/command_line/xtc_process.py, xfel/small_cell/small_cell.py
This pull request is related to the changes made in dials to use msgpack rather than pickle to serialize reflection data. https://github.com/dials/dials/pull/743
I have made some changes here to make sure that reflection files are serialized in the same way. Old reflection files in the pickle format can still be read using dials programs and if you used the dials.util.option.OptionParser class then pickle and msgpack files will be read transparently anyway.
=> Modified references to reflection pickle files from dials to use msgpack

xfel/command_line/cspad_cbf_metrology.py, xfel/command_line/cspad_detector_congruence.py, xfel/command_line/cspad_detector_congruence2.py, xfel/command_line/cspad_detector_shifts.py, xfel/command_line/cspad_detector_statistics.py, xfel/command_line/detector_residuals.py, xfel/command_line/filter_experiments_by_rmsd.py, xfel/command_line/frame_extractor.py, xfel/command_line/frame_unpickler.py, xfel/command_line/recompute_mosaicity.py, xfel/command_line/stills_merge.py, xfel/command_line/striping.py, xfel/command_line/xtc_process.py, xfel/small_cell/small_cell.py
**Note: Just an advisory pull request, not compulsory**
We've partially reverted the messagepack-as-default changes in [dials](https://github.com/dials/dials/commit/33fa5472920dbca6332b2391ea2951bf2a96b7c3) and [xia2](https://github.com/xia2/xia2/commit/082c6442f56cecc1ccd2933d169ee47a90aa4504) while we are reconsidering and handling a couple of related bugs relating to https://github.com/dials/dials/issues/770 that have stopped processing.
I believe this pull reverses, if you want, the parts of the cctbx/xfel code that was changed that is responsible for reading and writing only mpack files. I've attempted to leave in the parts of the code that handled both types. The idea is to re-revert these reversions once the underlying problem is fixed.
I don't know how urgently you need to use …
=> Advisory: Partially revert xfel messagepack changes

libtbx/env_config.py
With uwsgi, sys.prefix seems to be the name of the virtual environment, and os.path.split return the empty string for dirname. os.samefile than raises and exception, since stat fails for dirname.
=> Avoid OSError when cctbx.python is run with uwsgi

libtbx/auto_build/install_base_packages.py
1. Include more useful hint for resolving missing headers issue
2. Always build wxpython4 on Mojave since attempting to build wxpython3 fails
=> Bootstrap changes for Mac OS X 10.14 (Mojave)

iotbx/xds/xparm.py, rstbx/cftbx/coordinate_frame_helpers.py
this assumes XDS files are ASCII encoded, and that an encoding error means the format can not be understood.
Includes minor campsite improvements.
Tagging original authors for review.
=> Fix unicode issues in XDS parameter file readers

iotbx/detectors/dtrek.py, iotbx/detectors/pilatus_minicbf.py
* Usual necessary string/bytes modifications.
* Use context managers for file operations.
* Minor code cleanups.
Tagging original authors for review.
=> Fix dtrek and pilatus_minicbf formats for Python 3

iotbx/detectors/edf.py, iotbx/detectors/eiger_minicbf.py, iotbx/detectors/noir.py, iotbx/detectors/saturn.py
these are, as far as I can tell, the remaining iotbx/detector classes that are touched/covered by dxtbx tests:
edf, eiger minicbf, noir, saturn.
* Usual necessary string/bytes modifications.
* Use context managers for file operations.
* Minor code cleanups.
Not surprisingly this is very similar to the other pull requests. dxtbx tests on python 2 still pass.
Mentioning @nksauter and @phyy-nx for awareness
=> Fix further detector formats for Python 3

iotbx/detectors/detectors_ext.cpp, iotbx/detectors/raxisbase.py
in iotbx/detector/raxisbase.py.
Raw file data cannot be easily passed to and from the C++ helper
function. Luckily replacing the helper function with a pure python
generator is 3x faster anyway. Remove the C++ function as it is not
used elsewhere.
DIALS, dxtbx tests pass, no dxtbx 3 regressions
=> Python 3: Fix bytes/string/unicode boundary issue

xfel/command_line/xtc_process.py
This is no longer necessary due to changes in dxtbx regarding dynamic
masking
=> Removed MemMasker.

xfel/clustering/cluster.py, xfel/command_line/cspad_cbf_metrology.py, xfel/command_line/cspad_detector_congruence.py, xfel/command_line/cspad_detector_congruence2.py, xfel/command_line/cspad_detector_shifts.py, xfel/command_line/cspad_detector_statistics.py, xfel/command_line/cxi_index.py, xfel/command_line/cxi_merge.py, xfel/command_line/detector_residuals.py, xfel/command_line/filter_experiments_by_rmsd.py, xfel/command_line/frame_extractor.py, xfel/command_line/frame_unpickler.py, xfel/command_line/recompute_mosaicity.py, xfel/command_line/stills_merge.py, xfel/command_line/striping.py, xfel/command_line/xtc_process.py, xfel/cxi/util.py, xfel/merging/application/input/file_loader.py, xfel/merging/application/phil/phil.py, xfel/merging/application/worker.py, xfel/merging/command_line/merge.py, xfel/sacla/mpccd_geom2json.py, xfel/small_cell/small_cell.py, xfel/ui/command_line/plot_reflection_stats.py, xfel/ui/command_line/plot_run_stats_from_experiments.py, xfel/ui/command_line/plot_uc_cloud_from_experiments.py, xfel/ui/components/xfel_gui_init.py, xfel/util/dials_pickle_reader.py
This branch contains changes imposed by output file renaming in https://github.com/dials/dials/pull/822.
I'm not sure if these changes are complete, or if some errors have been introduced. I'm not very familiar with the cctbx.xfel code. So it wasn't always obvious to me when a pickle file is a dxtbx pickle or when it is a cctbx style integration pickle, or one of the other auxiliary pickles used by cctbx.xfel. There may be places where I have missed changes, or places where I have introduced unwanted changes.
Nevertheless, the tests in `libtbx.run_tests_parallel module=xfel_regression run_in_tmp_dir=true` pass, and do so on this branch whether or not DIALS is on https://github.com/dials/dials/pull/822, so at least under the coverage implied by these tests, backwards compatibility appears …
=> Rename output files

iotbx/detectors/__init__.py
requires recent dxtbx sources (after 12th of June) and a run of libtbx.configure.
=> fix dxtbx deprecation warnings

cctbx/crystal/__init__.py, cctbx/crystal/tst_ext.py, cctbx/regression/tst_crystal.py, cctbx/regression/tst_xray.py, cctbx/uctbx/__init__.py, cctbx/uctbx/boost_python/tst_uctbx.py
Add a more useful `__str__` output to crystal.symmetry:
```
>>> from cctbx import sgtbx
>>> cs = sgtbx.space_group_info("P1").any_compatible_crystal_symmetry(volume=1000)
>>> print(cs)
Unit cell: (8.52593, 11.0837, 14.4941, 83, 109, 129)
Space group: P 1 (No. 1)
```
=> Add __str__, __repr__ to crystal.symmetry, uctbx.unit_cell

boost/python.py, boost_adaptbx/meta_ext.cpp
FPE exceptions in Python inside development installations are no longer trapped by default, making the Python behaviour consistent with an environment from an installer. C++ exceptions continue to be trapped by default.
To re-enable traces set the environment variable `BOOST_ADAPTBX_ENABLE_TRACE`,
to re-enable FPE crashes set `BOOST_ADAPTBX_TRAP_FPE`,
to re-enable python overflow crashes set `BOOST_ADAPTBX_TRAP_OVERFLOW`.
Traps can be enabled for specific code sections using the context handler:
```python
import boost.python
with boost.python.trapping(overflow=True):
inf_value = 1e300
while inf_value != inf_value*inf_value:
inf_value *= inf_value   # crash
```
Right now the following two commands behave differently on any development installation:
```libtbx.python -c "import math; print …
```
=> Invert the BOOST FPE trap defaults.

libtbx/auto_build/bootstrap.py
This allows different build folders, for e.g. different configurations 
```
./bootstrap.py build --build-dir  cudabuild  --use_conda  --config-flags="--enable_cuda"  --builder=dials  
```
=> update to boostrap for build dir options

iotbx/shelx/parsers.py, smtbx/refinement/constraints/tests/test_occupancies.py
This pull requests fixes smtbx/refinement/constraints/tests/test_occupancies.py::test_simple_disorder on Python 3 (https://github.com/cctbx/cctbx_project/issues/364)
=> Use OrderedDict to guarantee order of constraints (fixes #364)

cctbx/command_line/cctbx_test_nightly.py, libtbx/auto_build/bootstrap.py
When running tests via bootstrap or buildbot then run the dxtbx and DIALS tests using pytest.
Please refer to the discussion in dials/dials#890 for background information.
For those actually running tests whis way:
What you may want to consider is whether you want to run the tests that depend on external data. My patch includes the `--regression` flag, so that data will be downloaded and the tests will be run. If you don't want to download the test data and/or run the extended tests then you can remove this flag. We DLS-folks won't mind either way as we do not use the bootstrap testing feature at all.
If you want to run the full test suite: I don't know how your buildbot setup is laid out, but if you do throw away the build directories between builds then you can save yourself time and …
=> Update DIALSBuilder to run DIALS and dxtbx tests

iotbx/cif/__init__.py, iotbx/cif/tests/tst_lex_parse_build.py, iotbx/command_line/merging_statistics.py, iotbx/merging_statistics.py, iotbx/mtz/__init__.py, iotbx/reflection_file_reader.py, iotbx/scalepack/no_merge_original_index.py, iotbx/shelx/hklf.py, iotbx/xds/integrate_hkl.py, iotbx/xds/read_ascii.py
- Add an `anomalous=None` parameter to `iotbx.mtz.object.as_miller_arrays()`.
- If this is set to `True` or `False`, then the call to `milller.set.auto_anomalous()` in `iotbx.mtz.column_group()` is avoided. This call can potentially be expensive with particularly large reflection files with millions of observations.
- In `iotbx.merging_statistics` pass the value of the anomalous parameter to
`iotbx.mtz.object.as_miller_arrays()`.
- Add anomalous parameters to other `as_miller_arrays()` methods
=> Optionally avoid auto_anomalous check in iotbx.mtz.object.as_miller_arrays()

scitbx/sparse/boost_python/matrix.cpp, scitbx/sparse/tests/tst_sparse.py
This pull requests adds pickling support for sparse matrices, which allows them to be used in multiprocessing, for example in sparse refinement code.
The state of the sparse matrix is stored as a list of tuples of row_index, column_index, value. I'm unsure how to reliably test the speeds of various implementations, but this seems the obvious choice to me.
=> Add pickling support for sparse matrices. For #195

xfel/command_line/detector_residuals.py, xfel/small_cell/small_cell.py
`flex.reflection_table.centroid_px_to_mm()` and `flex.reflection_table.map_centroids_to_reciprocal_space()` now take an `ExperimentList` as input instead of individual dxtbx models.
There don't appear to be any tests in the xfel module, so I wasn't able to verify that these changes actually work.
=> Synch with dials/dials#952

cctbx/miller/__init__.py, iotbx/shelx/hklf.py, iotbx/shelx/tst_hklf.py
A recent change (https://github.com/cctbx/cctbx_project/commit/4a7e1484d8db4c31d9d0189c7be0a9cf8cdb4e64) by @randyjread introduced a regression in the behaviour of `iotbx.shelx.hklf.miller_array_export_as_shelx_hklf`.  In introducing the `full_dynamic_range` argument, it seems he inadvertently deactivated the existing behaviour when `full_dynamic_range=False` and `scale_range` is not `None`.
This PR contains a simple fix that reinstates the option to run with `scale_range` set to a non-`None` value.  It also adds a test for that behaviour, to prevent future regressions, and also a basic test to exercise the `full_dynamic_range=True` behaviour introduced in https://github.com/cctbx/cctbx_project/commit/4a7e1484d8db4c31d9d0189c7be0a9cf8cdb4e64.
- Make it so that non-`None` values of …
=> Fix treatment of scale_range in hklf export

libtbx/env_config.py
We have had this problem for more than a year and I think this change may solve the problem.
It fixes compiling phaser_tng outside of conda on Windows with the following command:
`python bootstrap.py --builder=phaser_tng`
Without it the following error is reported:
`
RuntimeError: Multiple sources for dispatcher:
target file:
"c:\users\phaserbuilder\phasertng2\build\bin\phaser_tng.build_dag_node"
source files:
"c:\users\phaserbuilder\phasertng2\modules\phaser_tng\phaser_tng\command_line\build_dag_node.py"
=relocatable_path(anchor="c:\users\phaserbuilder\phasertng2\build", relocatable="..\modules\phaser_tng\phaser_tng/command_line\build_dag_node.py")
"c:\users\phaserbuilder\phasertng2\modules\phaser_tng\phaser_tng\command_line\build_dag_node.py" …
=> Fix necessary for compiling phaser_tng

libtbx/auto_build/install_conda.py
Following the lead of phenix dials now also includes conda environment definitions.
=> Add DIALS-specific conda environment

libtbx/pkg_utils.py
Tell setuptools to put the libtbx eggs in the build directory and eliminate the chdir around the setup() invocation.  This allows libtbx.refresh to run on a custom Python where write-access to site-packages directory is restricted.
=> Write the libtbx eggs to the build directory

iotbx/cif/__init__.py, iotbx/cns/index_fobs_sigma_reader.py, iotbx/dtrek/reflnlist_reader.py, iotbx/scalepack/merge.py, iotbx/solve/fpfm_reader.py
@phyy-nx I have fixed as much as I can, although I still get some errors which I think are related to missing dependencies (I have already checked out/configured phenix, phenix_regression, phenix_examples, elbow, plex,... and gave up after that).
It would be helpful if these particular reflection formats were exercised directly in iotbx, rather than relying on hard-to-access tests that rely on seemingly unrelated external dependencies.
```
Traceback (most recent call last):
File "/Users/rjgildea/software/cctbx/build/../modules/phenix/phenix/command_line/refine.py", line 11, in <module>
command_line.run(command_name="phenix.refine", args=sys.argv[1:])
File "/Users/rjgildea/software/cctbx/modules/phenix/phenix/refinement/command_line.py", line 86, in run …
```
=> Fixes for #395

scitbx/libtbx_refresh.py
Declares the random seeder in scitbx so that it can be controlled for testing.
(Feature mentioned in dials/dials#890)
Am I doing this right, @ndevenish?
=> Register scitbx flex arrays as random-seedable

xfel/command_line/cspad_cbf_metrology.py, xfel/command_line/cspad_detector_congruence.py, xfel/command_line/cspad_detector_congruence2.py, xfel/command_line/cspad_detector_shifts.py, xfel/command_line/cspad_detector_statistics.py, xfel/command_line/detector_residuals.py, xfel/command_line/experiment_json_to_cbf_def.py, xfel/command_line/filter_experiments_by_rmsd.py, xfel/command_line/find_highres_shots.py, xfel/command_line/frame_unpickler.py, xfel/command_line/recompute_mosaicity.py, xfel/command_line/striping.py, xfel/command_line/xfel_process.py, xfel/command_line/xtc_dump.py, xfel/command_line/xtc_process.py, xfel/merging/application/worker.py, xfel/sacla/mpccd_geom2json.py, xfel/small_cell/command_line/small_cell_process.py, xfel/small_cell/command_line/xfel_small_cell_process.py, xfel/small_cell/small_cell.py, xfel/ui/command_line/plot_reflection_stats.py, xfel/ui/command_line/plot_uc_cloud_from_experiments.py
Follows dials/dials#885 & dials/dials#860.  Fixes #385.
- Replace `dials.util.halraiser` with `dials.util.show_mail_on_error` context manager;
- Replace `dxtbx.model.experiment_list.ExperimentListDumper` and `dxtbx.serialize.dump` with `as_file` method of experiment list;
- Fix "DeprecationWarning: Setting verbosity for a Refiner is deprecated."
This conversion was largely automatic, performed at the same time as dials/dials#885.  There are only really three places where I used any judgement.  Once while applying the change necessary to match dials/dials#860 and twice while replacing `halraiser` calls.  The latter case, in particular, requires careful review since both instances are in sections of code for catching a race condition.  I haven't tested any of this, so you probably want to …
=> Fix deprecation warnings

iota/__init__.py, iota/components/gui/plotter.py, iota/components/iota_analysis.py, iota/components/iota_init.py, iota/components/iota_processing.py, iota/components/iota_ui_frames.py, iota/components/iota_utils.py, iota/doc/NOTES.txt
- fixed output path structure bug (integrated files, logs, etc. no longer
include pre-pended absolute path)
- input list is now sorted by filename (and then by image index if a multi-image
file)
- stdout capture no longer returns a "'unicode' does not have the buffer
interface" TypeError
- fixed plotting to account for an extra parameter (image index) when
calculating stats
- add picture file extensions (e.g. png, tiff, etc.) to image file tests
=> UI and backend bugfixes

libtbx/auto_build/bootstrap.py
We are running into build issues with SCons on Python 3. SCons 3.0 doesn't properly support Python 3, and a lot of fixes have been made to that version over the past 2 years, including one we need.
This updates SCons to the most recent 3.0 release by checking out the version directly from source, as suggested in https://github.com/cctbx/cctbx_project/pull/408#pullrequestreview-308331401
(This is currently holding up build-related work)
=> Update SCons to 3.0.5

iotbx/detectors/display.h
Handle `MASK_VAL` as set by dials/dials@874e6ba62a6 and stop treating all detectors as if `has_pilatus_inactive_flag == true`. For Pilatus-type images retain "-2" as the masked value for display. This branch also requires https://github.com/dials/dials/tree/non-pilatus-flags for changes to the image viewer
=> Masks for non-pilatus-like detectors

xfel/clustering/singleframe.py
Use radians, not degrees.  Caught by @nksauter.
The dials.cosym tests still pass.  Looking at them, I don't think they are clustering differing unit cells. 
test_cluster_unit_cell.py also still passes.  Looking at the output, the dendrogram produced by test_cluster_unit_cell.py is the same along x, meaning the same cells are associated with each other, but different along Y, meaning their relative scores are different.
If I run cluster.unit_cell on the 757 integration results in xfel_regression/prime_test_data/myo/integration, I get different numbers of singletons, so this change will affect scientific results.
@rjgildea, this is likely relevant to your interests.  Let me know if you want me to hold this.  Otherwise, I'll merge it tomorrow morning.
=> Longstanding bugfix for cluster.unit_cell

libtbx/env_config.py
This seems to be a suitable place to strip possible trailing directory separators from module names passed to `libtbx.configure`.
Fixes #427.
=> Strip trailing directory separators from module names.

wxtbx/metallicbutton.py
On wx 4.0.6 at least, which I am currently using, there is no Carbon.Appearance so work around - does not seem to have a measurable impact.
Maniftested in dials/dials#1091 which this commit will fix
=> Importing Carbon.Appearance fails

xfel/merging/application/errors/error_modifier_ev11.py, xfel/merging/application/errors/factory.py
Note: This pull request includes a fix to postrefinement that is currently broken on master.
Comparison with cxi.merge to ensure scientific correctness
Test dataset: run 105 from LD91, 2987 lattices
1. sdfac, sdb and sdadd values
| program | functional | sdfac | sdb | sdadd |
| --- | --| -- | -- | -- |
| xfel_merge | 64.42 | 5.31| 0.0  |  0.20 |
| cxi.merge | 79.23 | 5.88 | 0.0 | 0.18
2. Comparison of I/sigI for various resolution shells with cxi.merge on master
|Bin | Resolution Range |   xfel_merge | cxi.merge |
| ----| -------| ------| ------|
| 1  |-1.0000 -  4.3089    | 4.797 |    4.826
| 2 | 4.3089 -  3.4200    | 3.705  |   3.769
| 3 | 3.4200 -  2.9876    |  3.277  |  3.303
| 4 | 2.9876 -  2.7144   | 2.814   | 2.834
| 5 | 2.7144 -  2.5198   | 2.588  | 2.599
| 6 | 2.5198 -  2.3713 …
=> adding ev11 error model to xfel_merge

xfel/command_line/cspad_cbf_metrology.py
286a084 passes a wrong file name to `dials.refine` after the first level.
=> Repair cspad.cbf_metrology

libtbx/env_config.py, libtbx/pkg_utils.py
This is the conda-equivalent of the existing package management with pip
for base-ful installations.
Right now this only affects DIALS-native setups (`bootstrap.py --installer=dials` and equivalent) and is skipped for other cctbx bootstrapped conda environments, as it requires
1. the package `conda` to be installed as part of the conda environment (as far as I know this is not the case for any cctbx bootstrapped environments), and
2. the conda environment to be consistent (same)
Dependencies are declared in `libtbx_config` under the key `"conda_required"`,
the only packages declaring such dependencies at this time are DLS-internal packages.
The same exclusions apply as with the pip setup, that is if either
1. the environment variable `LIBTBX_DISABLE_UPDATES` is set, or
2. the installation …
=> Ensure conda dependencies are met for DIALS installations

libtbx/env_config.py
The current `get_gcc_version` function (in `libtbx/env_config.py`) deliberately returns `None` when `stderr` is non-empty. However, sometimes a compiler will output warnings in `stderr` (and still a valid version number in`stdout`). In these cases, the returned `None` can interfere with the build process.
This version still outputs `None`, if it fails to find a valid version number in `buffer.stdout`... so if your compiler is actually screwy, this is where the build system breaks (I guess that's what the `len(buffer.stderr)` business was all about).
=> Fix get_gcc_version so that it doesn't return 'None' when gcc emits warnings into stderr

rstbx/indexing_api/sampling.py
HemisphereSampler has an indentation error that makes it accept too many candidate basis vectors. This pull request fixes the error.  Datasets with weak signal and poor spotfinding parameters may see indexing rates go down a bit, but runtimes improve dramatically.  Strong data seems unaffected.
HemisphereSampler implements the Steller 1997 algorithm for choosing candidate basis vectors. Its method `get_top_solutions` is supposed to sort the putative basis vectors by their scores (kval), then pick the top 30 that are unique directions.  However, the current implementation keeps all non-unique vectors as it searches for unique ones, due to an indentation error in the python code. In some cases, this can lead to it returning thousands of candidates.
The algorithm iterates through each …
=> get_top_solutions bugfix for HemisphereSampler

simtbx/nanoBragg/__init__.py, simtbx/nanoBragg/tst_nanoBragg_cbf_write.py
Ful CBF writer for nanoBragg simulation, requires a change in dxtbx to be py2/3 compatible, which should be merged into dxtbx master shortly (relevant dxtbx branch is dxtbx_cbfwrite_py3compat)
=> Nano bragg cbfwrite

wxtbx/segmentedctrl.py
fix wxPython deprecation warning that is shown when using wxPython 4:
```
$ dials.reciprocal_lattice_viewer imported.expt strong.refl 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:
input {
experiments = imported.expt
reflections = strong.refl
}
Gtk-Message: 11:55:56.135: Failed to load module "pk-gtk-module"
Gtk-Message: 11:55:56.136: Failed to load module "canberra-gtk-module"
(...)/cctbx_project/wxtbx/segmentedctrl.py:46: wxPyDeprecationWarning: Using deprecated class. Use Control instead.
name=name)
```
Change seems to work on wxPython 3, so is probably harmless.
=> fix wxPython deprecation warning

libtbx/auto_build/install_base_packages.py
Without this simple patch I encounter this error during a fresh bootstrap:
[...]
===== Downloading http://cci.lbl.gov/repositories/tntbx.gz:  local copy is current (etag)
===== Running in modules: extracting files from tntbx.gz
===== Downloading http://cci.lbl.gov/repositories/clipper.gz:  local copy is current (etag)
===== Running in modules: extracting files from clipper.gz
removing .pyc files in /home/jan/Arbeit/cctbx-dev/modules, walk? True
removed 3 files
===== Running in .: base
****************************************************************************
Automated CCTBX dependencies build script
report problems to cctbx-dev@cci.lbl.gov
****************************************************************************
Setting up directories...
verifying _ssl installation in …
=> fixes a bytes string incompatibility on gentoo/sabayon

iotbx/detectors/display.h
Equivalent work to #415 but for multi-panel images.
Symptom: when clicking the 'show mask' button in the image viewer while a mask was loaded, the whole image would turn black for multi-panel images.  This is because the histogramming wasn't respecting the flag used to represent pixel values that have been masked, which is essentially the system's largest negative int.
Already reviewed by @nksauter.  He reports the additional time spent per image with this branch (due to the 2 new tests for the mask pixel value) is 0.023 seconds/ image for a Jungfrau 16M.  Any other comments welcome.
=> Use alternate pixel value for masking for multi-panel images

libtbx/auto_build/bootstrap.py, libtbx/auto_build/install_conda.py
From the discussion in #453 
When the `--use-conda` flag is used in `bootstrap.py`, an extra script is written that will activate the `conda` environment used for building before sourcing the standard setpaths script.
By default, there will be variations of the setpaths and unsetpath scripts named `conda_setpaths.sh/csh` and `conda_unsetpaths.sh/csh` for linux and macOS, and `conda_setpaths.bat` and `conda_unsetpaths.bat` for Windows. The prefix is `conda`, but that or the general filename can be changed.
This makes the packages (e.g. compilers, mpi, mysql, etc.) installed in the `conda` environment available along with the standard CCTBX build in a single script.
There may be issues as discussed in #145, but `conda` environments are more comprehensive than what we build with …
=> conda: add extra environment script

xfel/cxi/cspad_ana/cspad_tbx.py, xfel/cxi/cspad_ana/parse_calib.py
Output from running dxtbx tests:
```
====================================== warnings summary ======================================
modules/cctbx_project/xfel/cxi/cspad_ana/cspad_tbx.py:90
modules/cctbx_project/xfel/cxi/cspad_ana/cspad_tbx.py:90: DeprecationWarning: invalid escape sequence \S
'^(?P<det>\S+)\-(?P<det_id>\d+)\|(?P<dev>\S+)\-(?P<dev_id>\d+)$', address)
modules/cctbx_project/xfel/cxi/cspad_ana/cspad_tbx.py:96
modules/cctbx_project/xfel/cxi/cspad_ana/cspad_tbx.py:96: DeprecationWarning: invalid escape sequence \S
'^(?P<det>\S+)\.(?P<det_id>\d+)\:(?P<dev>\S+)\.(?P<dev_id>\d+)$', address)
modules/cctbx_project/xfel/cxi/cspad_ana/cspad_tbx.py:102
modules/cctbx_project/xfel/cxi/cspad_ana/cspad_tbx.py:102: DeprecationWarning: invalid escape sequence \( …
```
=> Fix invalid escape sequences

libtbx/SConscript
I found a failing test in `scitbx/lbfgs/tst_lbfgs_fem.py` while trying out compiling dials with conda compilers (dials/dials#1235 [(comment)](https://github.com/dials/dials/pull/1235#issuecomment-614516788)) and then saw the fix in 7976f7c16d7b941a236311d8c8fad36d36f04e24 coming through.
This fix however applies when using the system-native compiler, so I've also removed the flag when running with `compiler=conda` on MacOS.
I don't know if this is the best approach, and suspect @bkpoon will probably have a more well-informed opinion here. I didn't want to tie the flag to an xcode version because the compiler will be independent of that (and on the Mac that I'm running on there seems to be no xcode installed at all? Or maybe I'm just holding it wrong)
=> libtbx: remove -ffast-math flag for MacOS+conda

libtbx/env_config.py
Suggested solution for #399:
When configured with `--skip-phenix-dispatchers` but `phenix` being configured then ignore the `--skip` setting, as in this case the user is clearly interested in having phenix dispatchers available.
Could go a step further and eliminate the `--skip-phenix-dispatchers` flag entirely and only rely on whether phenix is configured.
=> ignore skip option if phenix is configured

libtbx/auto_build/package_defs.py
This is the final 2.7 release.
https://mail.python.org/archives/list/python-dev@python.org/message/OFCIETIXLX34X7FVK5B5WPZH22HXV342/
=> Update base installation to Python 2.7.18

iotbx/merging_statistics.py
If we create an instance of `iotbx.merging_statistics.dataset_statistics` with `anomalous=False` and pass an intensity array `i_obs` that is not a unique set under symmetry, but whose corresponding anomalous array is unique under symmetry (that is to say, an array in which the only symmetry-equivalent reflections are Friedel mates), we should be happy to calculate the non-anomalous merging statistics.  At present however, we raise a `Sorry` because the anomalous array is unique under symmetry, which is erroneous behaviour.
=> Fix check that a Miller array of intensities is not already merged

iotbx/merging_statistics.py, iotbx/regression/tst_merging_statistics.py
https://github.com/cctbx/cctbx_project/pull/477 changed the logic to decide whether data are already merged.  This PR introduces changes to the tests to accommodate the new behaviour.
The test data (`https://github.com/cctbx/cctbx_project/pull/477`) for the relevant tests are merged anomalous data.  When running `iotbx.command_line.merging_statistics.run` with the default parameter `anomalous=False`, we should therefore be able to calculate the merged non-anomalous data.  By contrast, with `anomalous=True` we should find that an exception (`Sorry`) is raised since the anomalous data are already merged.  These changes exercise that behaviour appropriately.
Also, I've tidied up `iotbx/regression/tst_merging_statistics.py` a little by removing some redundant parentheses and unused variables.
=> Add tests for fixed merging statistics logic

gltbx/SConscript
When compiling with conda compilers in a conda environment the system
includes and libraries are not considered by default. This works fine
for 99% of the build, however `libGL.so` is not included in a conda
installation.
gltbx has a check whether `libGL` can be compiled against, and if it can't
then it won't be built. Here we add a fallback solution: if `libGL` can't
be compiled against **AND** we are using conda compilers **AND** we are on linux
then try explicitly to compile against system libraries. If this is not
successful then skip as before, otherwise build gltbx using the system
libraries.
I haven't checked yet what happens on MacOS platforms
=> gltbx: use system libraries as fallback

cctbx/examples/merging/SConscript, scitbx/examples/bevington/SConscript
The logic in https://github.com/cctbx/cctbx_project/blob/2ce53dc81382c4761d8cf18d71b7276077e981fb/scitbx/examples/bevington/SConscript#L6 looks for eigen sources.
When `boost` is in `modules/` then it checks `modules/eigen`, however if conda boost sources are used it attempts to find the sources in `modules/cctbx_project/eigen` - it starts looking relative to `modules/cctbx_project/boost`.
Add a fallback that checks if the conda include path contains an `eigen3` directory, if so then use that one instead.
Related: dials/dials#1307
=> Look for conda eigen library as fallback

scitbx/suffixtree/boost_python/edge_exports.hpp, scitbx/suffixtree/boost_python/iterator_wrapper.hpp, scitbx/suffixtree/boost_python/object_extensions.cpp, scitbx/suffixtree/boost_python/suffixtree_single_ext.cpp, scitbx/suffixtree/edge.hpp, scitbx/suffixtree/edge.hxx, scitbx/suffixtree/iterator.hpp, scitbx/suffixtree/iterator.hxx, scitbx/suffixtree/matching_statistics.hpp, scitbx/suffixtree/test/tst_single.py, scitbx/suffixtree/tree.hpp, scitbx/suffixtree/tree.hxx, scitbx/suffixtree/word.hpp, scitbx/suffixtree/word.hxx
This fixes segfaults with Python2 and Python3 (tried with gcc 4.8 and 8.1 with debug and release modes).
=> Fixes to suffixtree

iotbx/reflection_file_reader.py
Do not give up when encountered non-mtz/pickle binary file (for example, gzipped cif files can be treated)
=> Updated try_all_readers()

prime/postrefine/mod_gui_dialogs.py, prime/postrefine/mod_gui_frames.py
Use plain `range` when in a context where an iterator is sufficient,
and explicitly convert to a list otherwise.
Remove one unnecessary intermediate list construction in a `max()` call,
where an iterator is sufficient.
(cf. #493)
=> prime: remove dependency on future/past package

libtbx/auto_build/bootstrap.py
DIALS now builds using C++11, so update the CCTBX bootstrap to reflect
this change, cf. https://github.com/dials/dials/pull/1235
Will merge when tests pass.
=> Enable C++11 for DIALS

cctbx/french_wilson.py
Allow these parameters to be set directly rather than having to construct and pass a phil params object. If a phil params object is passed, then values passed via that will take precedence.
=> Add max_bins & min_bin_size keywords

simtbx/nanoBragg/nanoBragg.cpp, simtbx/nanoBragg/nanoBragg.h
For now this code supports all use cases I have come across, including CSPAD and Jungfrau16M models. 
Things to consider:
0. Can we think of a better handedness test other than ```dot_product(pix0_vector, odet_vector)```? We have to compute the dot product regardless, so maybe this is fine as is.
1. The function ```init_beamcenter``` will sometimes recompute the ```odet_vector``` . If it does so then it checks the boolean ```detector_is_righthanded```, and rescales accordingly. 
2. Python-visible methods ```set_roi``` and ```set_beam_convention``` both call ```init_beamcenter``` under the hood. Could this get us into trouble ? 
3. Should we worry about the user that sets ```odet_vector``` manually, and unknowingly switches the hand ?
=> nanoBragg handedness

cctbx/adp_restraints/tst_ext.py, cctbx/geometry_restraints/tst_ext.py, dox/rst/installation.txt, libtbx/command_line/parallel_simple.py, libtbx/easy_mp.py, libtbx/python_code_parsing.py, scitbx/array_family/boost_python/tst_flex.py, scitbx/graph/rigidity_matrix_symbolic.py, sphinx/installation.rst, wxtbx/plots/__init__.py
remove some unnecessary compatibility constructs for unsupported python versions.
In particular the one in `wxtbx` caught my attention, as this (likely accidentally) globally disables `DeprecationWarning`s and `UserWarning`s based on the patch level of the python interpreter, ie. warnings are enabled on 2.7.4, disabled on 2.7.6, enabled on 3.6.5, disabled on 3.6.6, enabled on 3.7.3, etc...
The rest is mainly Python 2.2 and 2.6 compatibility stuff. The `sys.api_version()` used at one point has been a constant value (`1013`) since 2006.
=> Some code cleanup

iotbx/command_line/reflection_file_converter.py, iotbx/reflection_file_converter.py
The smx convention is to supply unmerged hkl files for refinement (where typically they get merged internally). This adds that option to reflection_file_converter. The reflection_file_converter dispatcher is also aliased within iotbx.
=> Add option to skip merging of input reflection files

scitbx/constants.h
SI definitions have changed on the 20th of May 2019:
https://en.wikipedia.org/wiki/2019_redefinition_of_the_SI_base_units
On that day the Planck constant and elementary electric charge were redefined
to be the exact values contained in this pull request.
=> Update scitbx to the current state of the universe

cctbx/miller/__init__.py, iotbx/regression/tst_merging_statistics.py
Only use reflections with multiplicity > 1. Variance is not defined for a single observation.
=> cc_one_half_sigma_tau bug fix

libtbx/auto_build/bootstrap.py
Due to the potential for more power outages at Berkeley. The
following packages were migrated to the CCTBX organization
on GitHub.com.
- annlib
- ccp4io_adaptbx
- clipper
- eigen
- gui_resources
- tntbx
The existing ccp4io repository is used instead of the one at Berkeley.
The official SCons 3.0.0 package is used instead of the copy at Berkeley.
=> bootstrap: migrate some CCI packages to GitHub

libtbx/auto_build/conda_envs/README.md
Small fixes for what I am guessing are typos in the readme e.g. 'python bootstrap' -> 'python bootstrap.py'.
=> Update conda_envs README.md

libtbx/env_config.py, libtbx/pkg_utils.py
This pull request reverts [#290](https://github.com/cctbx/cctbx_project/pull/290) and [#438](https://github.com/cctbx/cctbx_project/pull/438). The code in these pull requests was put in to ensure that software could declare its dependencies and when these dependencies change (as the software is living) the dependencies would auto-update. While this was useful for more than just DLS admin it was percieved at the time to be a DLS-only tool and met some resistance though has never been formally rejected or even properly discussed. 
We have however decided to revert these commits in the spirit of trying to improve the "mood" of the collaboration. Clearly this will have the side-effect that people using tools where the auto-update would have done something will now have to do this manually, …
=> No longer automatically update dependencies

rstbx/viewer/frame.py
As suggested by @dermen in https://github.com/dials/dials/issues/1442#issuecomment-709530168, this fixes the `dials.image_viewer` for me on Linux at least (ignoring 7 `wxPyDeprecationWarning`s)
=> Change required to fix e.g. dials.image_viewer on Linux

libtbx/auto_build/package_defs.py
`platform.dist` has been removed in Python 3.8, meaning that the
`create-installer` script fails. The code was only used to identify
CentOS 5, which has been out of support over three years, so this
should be safe to remove now.
=> Remove platform.dist() call in installer

libtbx/auto_build/install_conda.py
If we use an environment in a yaml file, then we call `conda env
create`, which does not have a -y flag. HOWEVER if the environment is
in a .txt file, we call `conda create`, which needs -y or it will wait
forever for confirmation.
@bkpoon Does this look ok? I believe this is the correct implementation of the original fix.
=> fix commit ffd70478

iotbx/mtz/extract_from_symmetry_lib.py, iotbx/xds/integrate_hkl.py, iotbx/xds/xds_inp.py, rstbx/cftbx/coordinate_frame_helpers.py
Seeing a bunch of these in dials tests:
```
cctbx_project/iotbx/mtz/extract_from_symmetry_lib.py:49: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/runner/work/1/modules/ccp4io/libccp4/data/symop.lib' mode='r' encoding='UTF-8'>
cctbx_project/iotbx/mtz/extract_from_symmetry_lib.py:49: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/runner/work/1/modules/ccp4io/libccp4/data/symop.lib' mode='r' encoding='UTF-8'>
cctbx_project/iotbx/mtz/extract_from_symmetry_lib.py:49: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/runner/work/1/modules/ccp4io/libccp4/data/symop.lib' mode='r' encoding='UTF-8'>
cctbx_project/iotbx/mtz/extract_from_symmetry_lib.py:49: ResourceWarning: unclosed file <_io.TextIOWrapper …
```
=> Fix ResourceWarnings

libtbx/introspection.py
observed a set of these in dxtbx tests
```
modules/cctbx_project/libtbx/introspection.py:232: ResourceWarning: unclosed file <_io.TextIOWrapper name='/proc/meminfo' mode='r' encoding='UTF-8'>
```
Again this is just using basic context managers, so will merge once tests pass.
=> Fix more ResourceWarnings

iotbx/data_plots.py, iotbx/regression/tst_data_plots.py
This would previously fail with e.g. `TypeError: %i format: a number is required, not NoneType`
=> iotbx.data_plots.table_data: column_formats bug fix if row contains None

crys3d/hklview/frames.py, rstbx/slip_viewer/frame.py, rstbx/viewer/frame.py, rstbx/viewer/processing.py, simtbx/nanoBragg/nanoBragg_gui_init.py, wxtbx/browser.py, wxtbx/custom_restraints.py, wxtbx/pdb_editor.py, wxtbx/plots/__init__.py, wxtbx/polygon.py, wxtbx/qstat_view.py, wxtbx/wx4_compatibility.py, wxtbx/xtriage.py
TB_3DBUTTONS is gone in wxpython 4.1.0 (dials/dials#1475).  This will affect any py3 wx4 compliant code that uses TB_3DBUTTONS.  Because of this I did a find/replace in cctbx_project to remove the style.
I tested removing TB_3DBUTTONS using cctbx.image_viewer in py2 and it worked with and without this change and without changing the toolbox visually.  So if phenix is using any of the files modified it should be ok.
=> TB_3DBUTTONS is deprecated

simtbx/nanoBragg/nanoBragg.cpp, simtbx/nanoBragg/nanoBragg.h, simtbx/nanoBragg/nanoBraggCUDA.cu, simtbx/nanoBragg/nanoBragg_ext.cpp, simtbx/nanoBragg/nanotypes.h, simtbx/nanoBragg/tst_gauss_argchk.py, simtbx/run_tests.py
In analyzing the GPU performance of the Mullen-Holton CUDA kernel, it was discovered that significant time is spent evaluating the exp() function in double precision, signifying the offset from the Ewald sphere.  This only applies to the GAUSS shapetype for the reciprocal lattice point.  Furthermore, the argument can be checked before evaluation; if the exp() result will be essentially zero, it can be skipped.  Thread warps where all exp() values are insignificant (away from reciprocal lattice points) will coalesce, saving measurable GPU wall clock time.  The new code offers a new shapetype, GAUSS_ARGCHK where the exp() argument is pre-evaluated.
Also modified:  correctly initializing integer arrays with integer literals
=> On GPU, pre-check the exp() argument for the Gaussian shapetype

libtbx/SConscript
Currently [MacOS conda builds are failing](https://dev.azure.com/azure-dials/dials/_build/results?buildId=1846&view=logs&j=ce2f6e73-8d2c-5881-d443-cea2c974a599&t=446b1ed1-c087-5c54-2034-4a043fb919b8&l=289) with
```
Done.
scons: Reading SConscript files ...
Compiler settings:
CC:  x86_64-apple-darwin13.4.0-clang
CXX: x86_64-apple-darwin13.4.0-clang++
RuntimeError: conda compilers are not installed.:
File "/Users/runner/work/1/build/SConstruct", line 6:
SConscript("libtbx/SConscript")
File "/Users/runner/work/1/conda_base/lib/python3.6/site-packages/SCons/Script/SConscript.py", line 661:
return method(*args, **kw)
File "/Users/runner/work/1/conda_base/lib/python3.6/site-packages/SCons/Script/SConscript.py", line 598:
return _SConscript(self.fs, *files, **subst_kw)
File …
```
=> allow relative paths for compilers

scitbx/array_family/boost_python/flex_int.cpp, scitbx/array_family/boost_python/tst_flex.py
Copies the integer array into a size_t array such that it can be used for
selections etc.
Fixes #580
Usage:
```
>>> from scitbx.array_family import flex
>>> a = flex.int(range(10))
>>> b = flex.int(reversed(range(10))
... )
>>> a.select(b)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
int.select(int, int)
did not match C++ signature:
select(scitbx::af::versa<int, scitbx::af::flex_grid<scitbx::af::small<long, 10ul> > > self, scitbx::af::const_ref<unsigned long, scitbx::af::trivial_accessor> indices, bool reverse=False)
select(scitbx::af::versa<int, scitbx::af::flex_grid<scitbx::af::small<long, 10ul> > > self, scitbx::af::const_ref<unsigned int, scitbx::af::trivial_accessor> indices, bool reverse=False) …
```
=> Add as_size_t method

libtbx/env_config.py
Had a user who was having issues running the conda cctbx package. Tracked down to the environment variable `LIBTBX_BUILD` being set, but empty, somewhere. Reproduction of same stacktrace:
```python
import os
os.environ["LIBTBX_BUILD"] = ""
import libtbx.load_env
```
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File ".../ENV/lib/python3.9/site-packages/libtbx/load_env.py", line 5, in <module>
libtbx.env = libtbx.env_config.unpickle()
File ".../ENV/lib/python3.9/site-packages/libtbx/env_config.py", line 3024, in unpickle
set_preferred_sys_prefix_and_sys_executable(build_path=build_path)
File ".../ENV/lib/python3.9/site-packages/libtbx/env_config.py", line 2920, in set_preferred_sys_prefix_and_sys_executable
if (dirname and op.samefile(build_path, dirname)): …
```
=> Handle case where LIBTBX_BUILD is set empty for conda install

iotbx/merging_statistics.py, iotbx/regression/tst_merging_statistics.py
This PR updates the key names for the `as_cif_block` method of the `iotbx.merging_statistics.dataset_statistics` class, to match the definitions of the pdbx mmcif v5 dictionary for the `reflns` and `reflns_shell` categories (https://mmcif.wwpdb.org/pdbx-mmcif-home-page.html).
The output now validates against v5 of the dictionary, according to the instructions in https://sw-tools.rcsb.org/apps/MMCIF-DICT-SUITE/README-source.
As an example, this was tested within a DIALS installation: 
`xia2 image=$(dials.data get -q x4wide)/X4_wide_M1S4_2_0001.cbf:1:20`
With the `master` branch, validating the output `xia2.mmcif` against the `mmcif_pdbx_v5_next.sdb` dictionary file gives the following errors, which are no longer present when running with this `mmcif_updates` branch:
```
ERROR - In block …
```
=> Update mmcif key names in as_cif_block method of iotbx.merging_statistics.dataset_statistics

iotbx/bioinformatics/__init__.py
sequence (and its subclasses) objects of this module are used in other modules, such as in the function get_muscle_alignment_ordered of mmtbx/msa.py, as immutable objects and in particular as keys of dictionaries. In Python3 immutable objects are required to implement the __hash__ method (if not obvious) and the __eq__ method. So I added the __hash__ method and I can continue to use that function correctly.
=> Adding __hash__ to sequence class

cctbx/miller/__init__.py
The current code means that anyone calling `miller.array.setup_binner_d_star_sq_step` and wishing to override the parameters `d_min` and `d_max` must pass `d_min=d_max` and `d_max=d_min`. The `binning` constructor takes arguments in the order `d_max`, `d_min`, i.e. the opposite order to order of the variable names when the constructor is called from the existing Python code.
https://github.com/cctbx/cctbx_project/blob/08b8e83bb3f9ebe47188ecea6eba7db1f8243942/cctbx/miller/bins.h#L44-L49
=> Make d_max and d_min the right way round

cctbx/miller/boost_python/match_indices.cpp, cctbx/miller/boost_python/tst_miller.py, cctbx/miller/match_indices.cpp, cctbx/miller/match_indices.h
Add a `match_indices` constructor that only takes one miller array.
Then use `mi.match_cached(h1)` as a replacement for `match_indices(h0, h1)`,
but called as follows:
```
mi = match_indices(h0)
mi.match_cached(h1)
```
before using `mi.pairs()`, `mi.singles(i)`, etc. This is faster when a single
array `h0` will be used to match several arrays `h1`, `h2`, ... because a lookup map
is constructed from `h0` and cached.
Another new member function `match_cached_fast` has the same call signature
as `match_cached`, but subsequently only `mi.pairs()` is available. This is
even faster when you only want the pairs.
=> Performance optimizations for cctbx::miller::match_indices

gltbx/fonts.py
I came across this function that appeared to be broken on Python 3, but is fixed by replacing a string literal with the equivalent bytes object.
=> A Python 3 fix for gltbx string rendering

iotbx/cif/validation.py
In some cases the reference obtained is not present in the dictionary. 
For example, ``_geom_bond_atom_site_label_1`` tag's reference is ``_geom_bond_atom_site_label_`` but that is not present in the Modulated Structures dictionary and it raises a KeyError: ``_geom_bond_atom_site_label_``.
This change tries to correct that error.
I'm attaching a CIF file that can serve as an example.
[bp5098Isup1.cif.txt](https://github.com/cctbx/cctbx_project/files/5924572/bp5098Isup1.cif.txt)
=> Correct problem with Modulated Structures dict.

xfel/ui/__init__.py, xfel/ui/db/frame_logging.py
* Refactor `DialsProcessorWithLogging` so that each event (shot) only logs one `db_event`. This makes all db queries independent so they can be batched.
* Add method `DialsProcessorWithLogging.log_batched_frames` and optionally call it from `log_frame`
* Add ui phil param `db.logging_batch_size`
=> Xfelgui batch logging

xfel/merging/application/modify/aux_cosym.py, xfel/merging/application/modify/cosym.py
This removes the overrides of some private methods. It wasn't clear to me what they were doing that was different to the original dials.cosym versions, and after removing them and falling back on the original dials implementations, the tests still pass.
Caveat: the cctbx.xfel cosym test currently fails as a result of https://github.com/cctbx/cctbx_project/issues/606, however after commenting out the `logger.debug` statement in https://github.com/dials/dials/pull/1647 the test passes.
See https://github.com/dials/dials/pull/1647
=> Compatibility with dials cosym clustering changes

iotbx/bioinformatics/pdb_info.py
We sometimes observe network timeouts in this test,
=> skip iotbx remote test if network connection flaky

scitbx/array_family/boost_python/tst_flex.py
We see these tests sometimes fail when the ABI shifts slightly, eg.
dials/dials#1001. Adding the tests here to catch these situations early.
So far, no clear idea what causes this.
=> Add ABI checks for `scitbx.flex`

iotbx/command_line/detector_image_as_png.py
With this fix, labelit.png (dispatcher for iotbx/command_line/detector_image_as_png.py) works in py3 (tested on dials_regression/image_examples/ALS_831/q315r_lyso_001.img)
=> Use bytes as IO for detector_image_as_png

scitbx/array_family/shared_plain.h
I want to make scitbx arrays whose memory is managed other than via malloc/delete. This isn't currently possible because  `sharing_handle` isn't polymorphic - it doesn't have a virtual destructor (or anything), so it's impossible to reliably override the implementation.
This patch changes that by:
- Making destructor and functions virtual
- Protect against SEGV or double-freeing of data from subclasses
=> Allow subclassing of sharing_handle

xfel/merging/application/modify/aux_cosym.py
After unit cell clustering, remove any filtered experiments from the
uuid_cache too.
=> Don't crash if experiments are lost in UC clustering step

boost_adaptbx/boost/python.py, libtbx/command_line/check_libcpp.py, libtbx/env_config.py
Problem statement: On Summit, "import boost.python" fails.
This is likely due to the practice, in high-performance computing centers, of linking the Python extension modules against one stdc++ library, whereas the system Python is linked against a different library behind the scene.
Solution: do not use ldd to check the libstc++ version in import-ext
The referenced code is part of the original cctbx design, but is likely not applicable to modern systems.
Removing it will save an external call to "ldd" during every boost python import.
=> Summit fix for libstc++

cctbx/miller/__init__.py, cctbx/regression/tst_miller.py
The previously locally-defined namedtuple result meant that the result of `iotbx.merging_statistics.dataset_statistics(..., anomalous=True, ...)` was not picklable.
Fixes xia2/xia2#611
=> Ensure anomalous_probability_plot is picklable

simtbx/kokkos/SConscript
Change SConscript to look for available (Nvidia) GPUs. If no Nvidia gpu is found, Intel Haswell architecture is assumed. The possible GPUs are V100 and A100.
=> Detect gpu architecture for kokkos

xfel/merging/application/README.md, xfel/merging/application/phil/phil.py, xfel/merging/command_line/merge.py
- User-created workers can be placed in ~/.cctbx.xfel/merging/application
(or linked there).
- Optional custom phil strings can be included with the worker.
- Documentation of custom workers is added in a new README
=> Add experimental support for custom merging workers

xfel/merging/application/group/group_reflections.py, xfel/merging/application/input/file_loader.py, xfel/merging/application/modify/polarization.py, xfel/merging/application/phil/phil.py, xfel/merging/application/reflection_table_utils.py, xfel/merging/command_line/merge.py
Importantly, introduced in the second commit,  the default now is to create and columns `is_even, is_odd, input_refl_index` in the reflection tables, and never prune them, optionally writing them to disk if save_experiments_and_reflections=True .
=> Merge bookkeeping

scitbx/matrix/__init__.py
The quaternion of a 0° rotation is, straightforwardly, 1.  Sometimes, since the axis direction for a 0° rotation is arbitrary, `axis_and_angle_as_unit_quaternion` may be called with an angle of 0 and a placeholder axis of (0, 0, 0).  In this case, return early to guard against a `ZeroDivisionError` when trying to normalise the axis.
=> Don't divide by zero if rotating by 0°

xfel/conda_envs/psana_environment.yml, xfel/conda_envs/psana_lcls_environment.yml
This reflects the resolution of #627 as discussed in several other issues
and PRs:
- https://github.com/boostorg/python/issues/376
- https://github.com/numpy/numpy/pull/20507
- https://github.com/numpy/numpy/pull/20616
Leaving this "bibliography" here because the fix in numpy PR 20616 is
considered temporary; thus someday we may have to revisit this to fix the
underlying bug in boost::python.
Co-authored-by: Billy Poon <bkpoon@lbl.gov>
=> Start allowing new numpy versions >=1.21.5

scitbx/math/boost_python/r3_rotation.cpp, scitbx/math/r3_rotation.h, scitbx/math/tests/tst_r3_rotation.py
Accept arrays of axes and angles. Test is added (which also demonstrates the
new usage).
@bkpoon @phyy-nx This was discussed briefly in #626 but got lost in the shuffle. I'll just merge it now provided that the tests pass.
=> New overload of scitbx.math.r3_rotation_axis_and_angle_as_matrix

mmtbx/masks/__init__.py
As discussed in https://github.com/cctbx/cctbx_project/issues/712 we've had to disable some xfel tests because the solvent mask generation gives new results since 2243cc9. This PR preserves the current default behavior (to my knowledge) but it makes two changes:
- Add a phil param for the max resolution at which solvent contributions are computed. This was previously hardcoded as 3Å.
- If `grid_step_factor` has been set, then `d_min` of the Miller array is passed to the `asu_mask` constructor. I don't see how `grid_step_factor` can be usable without this change.
When this PR is merged, we can temporarily add the following lines:
```
params2.mask.Fmask_res_high = 0
params2.mask.grid_step_factor = 4
params2.mask.solvent_radius = 1.11
```
to the places in `xfel/merging` and `LS49` where we …
=> Expose the "legacy" mask generation before 2243cc9 thru phil params

xfel/merging/application/model/crystal_model.py, xfel/merging/application/phil/phil.py, xfel/merging/general_fcalc.py
- cctbx.xfel.merge uses the mosaic model by default, but 'flat' is available
- cxi.merge uses the old (flat) model
=> xfel.merge and cxi.merge: handle the new mosaic solvent model

xfel/util/kapton_2019_correction_frame_frame_plugin.py
Adjust tolerance values in Kapton plugin These tolerances are associated with logic used to determine whether or not lines demarcating max/edge Kapton absorption intersect with detector panel(s). Tolerance values were increased by a factor of 3. This increase was chosen based on desired performance and ad hoc testing.
NOTE: This change will not work without pulling dials branch 'fix_max_edge_pt2'.
=> Modifications for Kapton Plugin: Part 2

xfel/merging/application/phil/phil.py, xfel/merging/command_line/merge.py
New defaults based on current usage:
- keep_imagesets is now True (able to do this because cctbx/dxtbx#438 is merged)
- postrefinement.enable now defaults to True.  To remove postrefinement manually, set it to False or remove the postrefinement worker
- Error model is now Ev11.  Because of this, errors_premerge worker is removed from the list of default workers as it is a no-op for Ev11
=> Update cctbx.xfel.merge defaults

libtbx/SConscript, libtbx/env_config.py, simtbx/SConscript, simtbx/kokkos/SConscript, simtbx/kokkos/detector.cpp, simtbx/kokkos/kernel_math.h, simtbx/run_tests.py
Spock uses AMD MI100 cards, which require HIP. This PR changes the build script so kokkos can be build with the HIP backend independent of cuda.
=> Decouple cuda and kokkos build for Spock

simtbx/gpu/gpu_ext.cpp, simtbx/kokkos/kokkos_ext.cpp, simtbx/kokkos/simulation.cpp, simtbx/kokkos/simulation.h
Each execution context now has two overloaded versions of exascale_api::add_energy_channel_mask_allpanel
=> Kokkos/CUDA equivalent interfaces for exascale_api

xfel/merging/command_line/merge.py
This optionally monkeypatches a couple `platform` functions that would normally create subprocesses to check the OS and architecture. Set environment variable `CCTBX_NO_UUID` to prevent creating these subprocesses.
Co-authored-by: Johannes Blaschke <jpblaschke@lbl.gov>
Co-authored-by: Nicholas Sauter <nksauter@lbl.gov>
Co-authored-by: Billy Poon <bkpoon@lbl.gov>
=> temporary fix for dials/dials#1998

xfel/small_cell/README.md, xfel/small_cell/command_line/powder_from_spots.py, xfel/small_cell/spotfinder_radial_average.py
Hi,
I have added optional simple interactive peak picking to xfel/small_cell/powder_from_spots, using the matplotlib window which was already generated. If a peak output file is specified, and the user clicks on the plot, the abscissa of the closest local maximum to the location of the click will be added to the peak file. While holding the mouse down a vertical line is shown to help placement.
This is my first time trying to contribute something to CCTBX so please forgive me if I got something wrong. I didn't see any folder with tests in the XFEL module so I wasn't sure how to add a test - but I swear my change doesn't break anything, it's extremely limited in scope.
Cheers,
David
=> interactive peak picking in powder_from_spots

scitbx/constants.h
This just adds neutron mass and Planck's constant to `constants.h`.
Naming and values based on `scipy.constants`.
=> Add the Planck constant and neutron mass to scitbx/constants.h

simtbx/nanoBragg/tst_nanoBragg_cbf_write.py, xfel/cftbx/detector/cspad_cbf_tbx.py
A recent bugfix (cctbx/dxtbx#488) added better flux support to the dxtbx Beam object.  In order to use it in simtbx's cbf [writing test](https://github.com/cctbx/cctbx_project/blob/master/simtbx/nanoBragg/tst_nanoBragg_cbf_write.py#L56), we have to add better support for reading and writing CBFs to the xfel cbf tool box, which is used by the dxtbx cbf writer.
Should be merged simultaneously with cctbx/dxtbx#493
=> Fix simtbx flux test

simtbx/kokkos/SConscript
o Build architecture-appropriate kokkos and kokkos-kernels targets
for corigpu, spock, crusher, darwin volta-x86, and darwin
shared-gpu-ampere nodes
=> Machine support for kokkos cmake builds

.azure-pipelines/xfel/download-source.yml, .azure-pipelines/xfel/unix-conda-build.yml, .azure-pipelines/xfel/unix-psana-build.yml, simtbx/SConscript, simtbx/kokkos/SConscript, simtbx/run_tests.py
Co-authored-by: Felix Wittwer <fwittwer@lbl.gov>
Co-authored-by: Billy K. Poon <bkpoon@lbl.gov>
Co-authored-by: Nicholas Sauter <nksauter@lbl.gov>
=> Add kokkos and its simtbx/LS49 tests to Azure build

xfel/SConscript
At the moment, these variables are defined in both XFEL and DIALS, because dials might be configured after XFEL in the module load order. This change continues the current behaviour, but in cases where DIALS has already set the variables, they will not be overwritten.
=> xfel SCons: Don't overwrite dials helper vars if already set

simtbx/kokkos/SConscript
This way we can use the `KOKKOS_HOST` environment variable to switch between generic kokkos hosts (eg. when testing on systems that are not on the known hosts list)
=> Add generic linux a100 host for kokkos

rstbx/symmetry/constraints/a_g_conversion.h, rstbx/symmetry/constraints/parameter_reduction.py
Indexing NaCl neutron data with DIALS gives a P1 volume lower than the current hard-coded threshold in rstbx. The highest symmetry solution is an almost perfect fit with the experimental result (5.64, see below), so fairly confident the P1 cell is valid.
=> Lower hard-coded unit cell limit from 70 A^3 to 40 A^3

iotbx/reflection_file_reader.py, iotbx/regression/tst_reflection_file_utils.py, iotbx/shelx/crystal_symmetry_from_ins.py, iotbx/shelx/lexer.py
It broke the use of
reflection_file_reader.any_reflection_file(hklfn+'=hklf+ins/res')
This feature had no test and it did therefore went unnoticed.
=> Fix a bug introduced in #5ae04d2955fa

.gitmodules
This updates the xfel/euxfel/definitions submodule so that it points to nexusformat/definitions instead of HDRMX/definitions.  The former is up to date and should have anything needed that was put into HDRMX.
We at least need this to work around a [syntax error](https://github.com/HDRMX/definitions/blob/master/manual/source/examples/h5py/TestWriter.py#L68) in HDRMX that isn't in nexusformat.
I had to run these commands to pick up the change (not needed for general cctbx users, just those running NeXus EuXFEL stuff):
```
git submodule sync --recursive
git submodule update --init --recursive --remote
```
@kirienko in your original PR #623, you [commented](https://github.com/cctbx/cctbx_project/pull/623#issuecomment-863398026) you needed to check if nexusformat/definitions has everything you …
=> Update submodule xfel/euxfel/definitions to point to nexusformat

simtbx/gpu/tst_exafel_api.py, simtbx/nanoBragg/__init__.py, simtbx/nanoBragg/nanoBragg.cpp, simtbx/nanoBragg/nanoBragg.h, simtbx/nanoBragg/nanoBragg_ext.cpp, simtbx/nanoBragg/tst_gauss_argchk.py, simtbx/nanoBragg/tst_nanoBragg_cbf_write.py
Use an output scale producing visible Bragg spots. Output scale is applied as a function argument to SMV writer But with CBF it is a multiplier to the actual pixels Verify both files (CBF, double) and (SMV, int) have same pixel values to within rounding error.
Run the test with libtbx.python tst_nanoBragg_cbf_write.py
View the two result images with dials.image_viewer test_full_100.*
=> Reconcile SMV and CBF writers in nanoBragg.

libtbx/auto_build/conda_envs/cctbx.devenv.yml, libtbx/auto_build/conda_envs/cctbxlite.devenv.yml, libtbx/auto_build/install_base_packages.py, libtbx/pkg_utils.py
As discussed in: https://github.com/pypa/setuptools/issues/3297 it seems that importing pip is just not supported. Our use case was not really compelling, we were (1) checking the version and (2) using a `pip._internal.main` api which is a thin (and to be deprecated) wrapper over `pip._internal.cli.main.main` There's a clear discussion here: https://pip.pypa.io/en/stable/user_guide/#using-pip-from-your-program of why using pip via `subprocess` is preferred. 
This is a draft because there's a second place in `libtbx/auto_build/install_base_packages.py` where `pip._internal.main` is used in a similar way.
=> Stop importing pip, use subprocesses instead. Will close #710

libtbx/env_config.py
In https://github.com/pypa/setuptools/pull/3265 (merged in setuptools 64), the default behavior of `pip install --editable` changed. This broke the libtbx.refresh scripts that previously placed an entrypoints file in `modules`, e.g. `modules/dxtbx/src/dxtbx.egg-info/entry_points.txt`.
We restore the legacy behavior by setting an environment variable `SETUPTOOLS_ENABLE_FEATURES=legacy_editable` before running the libtbx_refresh scripts. This allows using the current setuptools, otherwise we would have to pin it again to <=63.
=> libtbx_refresh runs with setuptools in "legacy_editable" mode

simtbx/gpu/detector.cu, simtbx/gpu/detector.h, simtbx/gpu/gpu_ext.cpp, simtbx/gpu/simulation.cu, simtbx/gpu/simulation.cuh, simtbx/gpu/simulation.h, simtbx/gpu/tst_exafel_api.py, simtbx/gpu/tst_shoeboxes.py, simtbx/gpu/tst_unified.py, simtbx/kokkos/detector.cpp, simtbx/kokkos/detector.h, simtbx/kokkos/kokkos_ext.cpp, simtbx/kokkos/kokkos_utils.h, simtbx/kokkos/simulation.cpp, simtbx/kokkos/simulation.h, simtbx/kokkos/simulation_kernels.h, simtbx/run_tests.py
Accordingly, retire tst_kokkos_lib in run_tests.py. Switch contexts with a command-line flag.
=> Generalize tst_exafel_api to both cuda and kokkos

xfel/swissfel/jf16m_cxigeom2nexus.py
- Handle images without a corresponding spectrum by filling in energy=0.0001 eV
- Add phil param for pulse ID offset between spectra and images
Co-authored-by: Iris Young <idyoung@lbl.gov>
=> SwissFEL updates from P20231

simtbx/kokkos/kokkos_ext.cpp, simtbx/kokkos/simulation.cpp, simtbx/kokkos/simulation.h, simtbx/kokkos/simulation_kernels.h, simtbx/run_tests.py
Within the exascale_api, most API functions are now subject to identical tests in both the cuda and kokkos_gpu contexts.  This commit adds a test for the add_background() function, tested with a multi-source beam model.
=> Implement kokkos_gpu version of gpu test.

xfel/merging/application/phil/phil.py, xfel/merging/application/scale/experiment_scaler.py
This refactors the xfel.merge experiment_scaler to use `scipy.stats.pearsonr` and `scipy.optimize.curve_fit` to compute the correlation coefficient and scale factor. This facilitates further improvements like new weighting schemes for fitting scale factors. The "icalc" weighting here gave a big improvement in a smSFX dataset, from R1 12.8% to 9.6%.
=> Scipy scaling

xfel/util/weather.py
I have removed some repetition and unused variables from the weather plot at `xfel/util/weather.py`. New script additionally outputs the five number summary of individual ranks' wall times. I used that in conjunction with a bash script to quickly find wall times of all individual indexing tasks. Consider rejecting if this functionality is already present in cctbx. The plotting itself should not be affected.
Current output format:
debug_1.txt
...
debug_127.txt
Five number summary of 9056 fail image processing times: 1.427, 1.549, 1.616, 2.490, 41.423
Five number summary of 694 good image processing times: 11.510, 24.707, 29.495, 36.216, 77.082
Suggested output format:
Five number summary of 9056 fail image processing times:   1.427,   1.549,   1.616,   2.490,  41.423
Five number summary of …
=> Better weather

xfel/command_line/cxi_mpi_submit.py, xfel/ui/__init__.py, xfel/ui/command_line/ui_server.py, xfel/ui/components/submission_tracker.py, xfel/ui/components/xfel_gui_dialogs.py, xfel/ui/db/job.py, xfel/util/mp.py
The desired behavior of this PR is to add the required UI features to enable a user to start a database server from the UI. The main changes are:
1.  Logic added to create new dialog boxes to guide user to add required info to start DB server in /ui/components/xfel_gui_dialogs.py
2.  Small changes  in /ui/command_line/ui_server.py to ensure backwards compatibility of ui_server.py
3. Add in more phil parameters in /ui/__init.py__ necessary to support ability to launch server from GUI
4.  Add args in `do_submit` function in command_line/cxi_mpi_submit.py to pass in log and err file names- helpful to diagnose potential db issues
5. Added new method to class QueueInterrogator in /components/submission_tracker.py to retrieve name of host running server on NERSC and write to phil parameters
6. …
=> Add button to start mysql server

.azure-pipelines/xfel/download-source.yml, xfel/merging/application/balance/load_balancer.py, xfel/merging/application/errors/error_modifier_ha14.py, xfel/merging/application/filter/experiment_filter.py, xfel/merging/application/filter/reflection_filter.py, xfel/merging/application/group/group_reflections.py, xfel/merging/application/input/file_loader.py, xfel/merging/application/integrate/integrate.py, xfel/merging/application/lunus/lunus.py, xfel/merging/application/modify/cosym.py, xfel/merging/application/modify/polarization.py, xfel/merging/application/modify/reindex_cosym.py, xfel/merging/application/modify/reindex_to_reference.py, xfel/merging/application/phil/phil.py, xfel/merging/application/postrefine/postrefinement_rs.py, xfel/merging/application/postrefine/postrefinement_rs2.py, xfel/merging/application/reflection_table_utils.py, xfel/merging/application/scale/experiment_scaler.py, xfel/merging/application/statistics/experiment_resolution_statistics.py, xfel/merging/application/statistics/intensity_resolution_statistics.py, xfel/merging/command_line/merge.py, xfel/merging/command_line/mpi_integrate.py, xfel/merging/ext.cpp
Closes dials/dials#1858.
Background: exp_id is a column of experiment identifiers, originally developed in parallel with the experiment_identifier map in DIALS.  Now that the experiment_identifier map is standard in DIALS, exp_id is redundant, so this PR removes it.
Note this PR makes heavy use of two convenience methods in DIALS:
- [concat](https://github.com/dials/dials/blob/main/src/dials/array_family/flex_ext.py#L511-L527): takes two or more reflection tables and concatenates them together, renumbering the `'id'` column and taking care of the experiment_identifer map
- [reset_ids](https://github.com/dials/dials/blob/main/src/dials/array_family/flex_ext.py#L1224-L1236): resets the `'id'` column, accounting for any gaps. Useful after using `select` to remove reflections from a table.
=> Remove exp_id from cctbx.xfel.merge

xfel/cxi/cspad_ana/rayonix_tbx.py
After merging this, the min_trusted_value set here:
https://github.com/cctbx/dxtbx/blob/450277d94596c980762ae30f58fa357a37a1d642/src/dxtbx/format/FormatXTCRayonix.py#L71-L74
will be correct and the saturated_value can be corrected to the new `rayonix_max_trusted_value`.
=> update rayonix trusted values to match convention in cctbx/dxtbx#536

xfel/merging/application/integrate/integrate.py
Tiny commit, but since it modifies return type/value of Integrate worker, hence PR. 
When merging data after ensemble refinement, I encountered the following error:
File ".../cctbx/modules/cctbx_project/xfel/merging/application/integrate/integrate.py", line 63, in run
self.logger.log("Integration done, %d experiments, %d reflections"%(len(all_integrated_expts), len(all_integrated_refls)))
TypeError: object of type 'NoneType' has no len()
The default behavior for Integrate worker is: define `all_integrated_refls` as None (line 34) and replace it with integrated reflections as soon as you find any (line 61). However, if no reflections are found `all_integrated_refls` will remain `None` which will raise said `TypeError` when prompted for len().
In this PR I assumed that an expected behavior …
=> Prevent `all_integrated_refls = None` returned by integrate worker

xfel/merging/application/errors/error_modifier_ev11.py
Work around for when ev11 gets a negative global_sum_of_delta_squared_in_bin for a given bin.
The test case I have shows that the refinement takes a bad step giving a high target function value, even if I throw out a bad bin.  It then recovers the minimization procedure:
```
5669.41
5669.41
2638.52
2571.27
2291.39
1115.96
2253525.53  <-- this is the bad step with the single bin that needs to be thrown out to avoid a math domain error
1115.78
2289.79
943.97
936.21
927.23
918.19
868.21
803.22
799.45
```
=> Work around for ev11 crash

xfel/cftbx/detector/cspad_cbf_tbx.py, xfel/cxi/cspad_ana/rayonix_tbx.py
- Start adding `underload`, which is the minimum trusted value, to CBFs.
- Set CBF `overload` to the smallest untrusted value
- Use rayonix_max_trusted_value instead of rayonix_saturated_value when setting trusted ranges.
This supersedes #826.
=> CBF trusted range updates

.azure-pipelines/xfel/conda-linux.yml, .azure-pipelines/xfel/unix-psana-build.yml, xfel/conda_envs/psana_environment.yml
The psana=4.0.47 and h5py<3.2 pins are mutually incompatible, apparently related to the packages zlib/libzlib. The h5py issue in h5py/h5py#1880 and conda-forge/h5py-feedstock#92 is no longer reproducible. The problem with C++ compiler standard for boost 1.78 was resolved by 47c364ac, meaning that psana can now be unpinned. Therefore it appears we can unpin everything and monitor for regressions when using h5py.
=> Unpin everything

xfel/ui/components/xfel_gui_controls.py, xfel/ui/components/xfel_gui_init.py
The aim of this PR is to introduce a correct numeric sort for columns "Job" and "Task" in cctbx.xfel GUI. These columns display (usually) integers as strings, which according to default sort result in `- < 12 < 123 < 2 < 23`. This is clearly expected, but unintended.
With my limited experience I couldn't find build-in natural column sorter, but I wrote a custom one which handles the issue using try-except statements. This sorter assigns unconvertable strings such as ` ` or `-` value of -1073741820 (slightly shy off half the minimum 32-bit integer, -1e99 caused SegFault). This new sorter acts on columns "Job" and "Task", and does not appear to be slower than the built-in one, although the largest table I could test on had barely 1000 rows.
Additionally, I replaced some mutable default …
=> Sort jobs correctly in cctbx.xfel jobs tab

xfel/merging/application/filter/experiment_filter.py, xfel/merging/application/phil/phil.py
This is motivated by the use case where a pseudomerohedral indexing ambiguity is resolved by unit cell clustering and manual reindexing. For example: for an orthorhombic unit cell 100 x 102 x 150 A, there is a pseudomerohedral indexing ambiguity around the rotation axis a+b. The misindexed lattices will cluster around 102 x 100 x 150 A. If the clusters are separable, then this is resolved by separately isolating the second cluster and reindexing it with modify_reindex_to_reference, then merging both clusters (which are now indexed consistently).
The skip_component parameter is needed because this approach fails if an experiment belongs to both components and thus appears twice in the final merge. Therefore when we isolate component 1, we exclude any experiment that also matches component …
=> experiment_filter: add ability to exclude cells matching a cluster

gltbx/wx_viewer.py
This fixes:
```
TypeError: Timer.Start(): argument 1 has unexpected type 'float'
```
observed with wx 4.2.0 when trying to run `cctbx.multiplicity_viewer`
=> wx.Timer.Start expects an integer value for milliseconds.

wxtbx/segmentedctrl.py
These changes were required to get the `dials.reciprocal_lattice_viewer` working without error. There are probably other occurrences elsewhere.
=> For wxpython 4.2.0 these functions expect certain parameters to be int.

.azure-pipelines/py2_syntax_exceptions.txt, xfel/util/drift.py, xfel/util/drifter.py
Improve robustness and plotting capabilities of the `drift.py` (previously `drifter.py`) tools. Allow reading and visualizing series of data (instead of averages/firsts only) by modifying existing reading tools and drawing with 2D heat maps. New capabilities are available via phil parameters. Some steps still need to be taken to increase the robustness of `DriftScraper` and `DriftTable`; this will be handled in near future.
=> Better detector drift scraping and visualizing

kokkostbx/SConscript, simtbx/kokkos/SConscript
This PR removes the duplicated kokkos build in `kokkostbx` and `simtbx/kokkos`. From now on, only kokkostbx will build the kokkos library files. This PR also fixes a bug on Perlmutter and Frontier caused by conda libssh.
=> Update kokkos build

xfel/merging/application/merge/merger.py, xfel/merging/application/phil/phil.py, xfel/merging/application/reflection_table_utils.py
I made this change to add variability to CC1/2, but I failed to notice there was an existing phil switch for this: `statistics.cc1_2.hash_filenames` . However, when I tested `hash_filenames=True`, it didnt seem to randomize CC1/2.. Anyway, id like this functionality..
=> shuffle ids for even/odd merge stats

simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp
This commit fixes the uninitialized variables in diffBragg_kokkos_kernel.cpp, mentioned in #879
=> fix uninitialized variables in diffBragg

simtbx/diffBragg/src/diffuse_util.h, simtbx/diffBragg/src/diffuse_util_kokkos.h
o Previous principal axes were a, b, c
o New principal axes are a-b, a+b, c
o New axes enable simulation of Wall et al, Structure 1997 calmodulin data
- Like Figure 7 in the Young et al. Methods in Enzymology Erice paper
=> Rotate axes for diffBragg anisotropic diffuse

simtbx/diffBragg/hopper_io.py
This miniature PR will cause `simtbx.diffBragg.hopper` (or just `hopper`) to preserve the experimental identifier when saving a refined expt file from Modeler. I am staging the change here as a PR instead of committing directly mostly to avoid getting put on the blame list, as the current master does not build properly, and to remember to commit eventually.
=> Preserve `expt.identifier` in diffBragg hopper

iotbx/regression/tst_hierarchy_long_chain_ids_1.py, simtbx/diffBragg/src/diffuse_util.h, simtbx/diffBragg/src/diffuse_util_kokkos.h
Normalize rotation matrices used to apply diffuse symmetry in diffBragg
o Required to make a number of them proper rotation matrices 
o Also add some comments and change matrix name to clarify what's
going on when the principal axes of the diffuse model are rotated
=> Normalize diffuse rotations

simtbx/diffBragg/utils.py, xfel/merging/application/model/crystal_model.py, xfel/merging/general_fcalc.py
Preparing to eliminate iotbx.pdb.hierarchy.input class, which will change the outcome of any_file() when reading model files. It will return iotbx.pdb.
file_reader.any_file().xray_structure_simple() indeed calls the same code as pdb.input().xray_structure_simple().
=> Refactoring out any_file usage where the type of the file is obvious.

xfel/command_line/cspad_detector_congruence.py, xfel/command_line/cspad_detector_congruence2.py, xfel/command_line/detector_residuals.py, xfel/metrology/panel_fitting.py
In `cctbx.xfel`, the `matplotlib` colormaps are sometimes accessed using `matplotlib.cm.get_cmap`, which is deprecated starting from matplotlib version 3.7, see issue #894. This PR replaces these calls with a supported equivalent `plt.get_cmap`.
Furthermore, while browsing for colormap usage in cctbx, I have found multiple instances of colormaps being accessed directly, e.g. `matplotlib.cm.jet`. This way of accessing colormaps works in maplotlib 3.7 without raising a warning. I asked the developers whether this interface is expected to stay and currently left this code as-is.
=> Use `mpl.plt.get_cmap` instead of deprecated `mpl.cm.get_cmap`

iotbx/merging_statistics.py, iotbx/regression/tst_merging_statistics.py
Upon iterating through the name dict, the test for finding the string 'percent' should be on the keys, not the values.
Added a line to a test to verify. This issue means that when the merging stats were converted to a cif block, the `_reflns.percent_possible_obs` item has been in the range 0 -> 1 rather than 0 -> 100 as intended.
=> Fix bug in merging_statistics.as_cif_block function

mmtbx/scaling/absolute_scaling.py
With the previous code, if `number == d_star_sq_hkl.size()` then the following line would fail with `IndexError` (https://github.com/xia2/xia2/issues/749):
```
self.kernel_width = d_star_sq_hkl[sort_permut[number]]-d_star_sq_low
```
The change ensures that `number` does not exceed `d_star_sq_hkl.size()-1`
=> absolute_scaling IndexError

xfel/small_cell/small_cell.py
This PR splits out the lattice determination part of `small_cell_index_detail` into a new function, `small_cell_index_lattice_detail`, so that this could be called by `dials.index`. This is necessary because `dials.index` loads experiments with `check_format=False`, so fails on the subsequent parts of the original function where the pixel data are accessed.
During the refactor, a certain amount of tidying-up was also done, such as reducing nested indents.
This PR has been tested to give the same results as `main` on this test case:
```
cd $(dials.data get -q 4fluoro_cxi)/lcls_2022_smSFX_workshop_data/indexing/
cctbx.xfel.small_cell_process params_1.phil ../ten_cbfs/*.cbf
```
Before a `small_cell` indexer is added to DIALS, @phyy-nx noted that it may be worth moving this code to …
=> Refactor `small_cell_index_detail`

xfel/merging/application/scale/experiment_scaler.py
The experimental scaling worker prints to the log that scaling did not occur when it actually did.
=> Log file was incorrectly displaying scaling was not performed

libtbx/mpi4py.py
This prevents confusing error messages in some cases where the system has mpi4py but we are running single-process. One example is `cctbx.xfel.merge -h`, which currently prints:
```
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
at the end of its output because it hits a SystemExit inside the wrapped function. With this PR, in the given case we won't attempt to clean up the nonexistent MPI communicator.
=> mpi_abort_on_exception: do nothing if communicator size is 1

simtbx/kokkos/simulation.cpp, simtbx/kokkos/simulation_kernels.h
Debranch kernel now a) uses vec3 rather than Holton-vec4; b) marshals all mos-tics and phi-tics into one list of crystal orientations; c) aligns exact order of operations (*,/) with kokkosSpotsKernel.
=> Streamline the two exascale simulation kernels.

boost_adaptbx/SConscript, boost_adaptbx/tests/python_streambuf_test_ext.cpp, cbflib_adaptbx/detectors/cbf_adaptor.h, cctbx/math/SConscript, cctbx/math/time_trigonometry.cpp, scitbx/lbfgsb/boost_python/SConscript, scitbx/lbfgsb/dev/SConscript, scitbx/lbfgsb/raw.h, spotfinder/core_toolbox/libdistl.cpp
- Change header from boost/timer.hpp to boost/timer/timer.hpp
- Change boost::timer to boost::timer::auto_cpu_timer
- Handle switch to nanoseconds
- Build Boost timer library if needed
Fixes  #944
=> boost: switch deprecated boost/timer.hpp to boost/timer/timer.hpp

.azure-pipelines/py2_syntax_exceptions.txt, xfel/command_line/drift.py, xfel/command_line/preference.py, xfel/command_line/preferential_orientation.py, xfel/merging/application/preference/factory.py, xfel/merging/application/preference/preference.py, xfel/util/drift.py, xfel/util/preference.py, xfel/util/preferential_orientation.py
This PR introduces a method to analyze the kind and degree of preferential orientation across multiple experiments. The method can be accessed in two different ways. Firstly, it is accessible as a standalone tool via `cctbx.xfel.preference`, providing a quick method to analyze small amounts of data. Additionally, preferential orientation can be analyzed via a dedicated `cctbx.xfel.merge` worker called `preference`, which takes no phil parameters and can be easily introduced before merging. Both methods can be run using MPI.
The degree of preferential orientation, i.e. the "preference", is evaluated by fitting a Watson Distribution to the list of normalized lattice directions across all experiments. The [Watson distribution](https://doi.org/10.2307%2F3213566) is a conceptually simple …
=> Evaluation of preferential orientation

cctbx/miller/__init__.py
I came across this whilst running [this script](https://github.com/dials/dials/issues/2625#issuecomment-2015145506) on data in space group $F d d 2$. Simplest solution: if `label_string()` returns `None` just wrap it in a `str()` call.
=> Fix miller array `repr` when `label_string()` returns `None`

cctbx_website/html_files/doc_models_hierarchy.html, mmtbx/command_line/clashscore2.py, mmtbx/programs/clashscore2.py, mmtbx/programs/probe2.py, mmtbx/programs/reduce2.py, mmtbx/reduce/Optimizers.py, mmtbx/validation/clashscore2.py
Adds a clashcore2 program that mirrors the clashscore program but it uses mmtbx.reduce2 and mmtbx.probe2 rather than phenix.reduce and phenix.probe.
It takes the same command-line programs as the original except for time_limit and it also supports probe PHIL parameters.
=> Clashscore2

mmtbx/hydrogens/reduce_hydrogen.py, mmtbx/programs/reduce2.py
Makes Reduce2 use the same wrapping of Probe2 that Clashscore2 uses, which is much cleaner.
Factoring out argument construction in reduce_hydrogens.py so that it can be reused in reduce2.py.
=> Reduce2 updates

mmtbx/scaling/data_statistics.py, mmtbx/scaling/twin_analyses.py
Fix a couple of places in `mmtbx.scaling` where the attribute of a class, initially set to `None`, is implicitly expected to have since become an `int`.  There are seemingly valid paths through the code in which the attribute values remain `None`, so this leads to a comparison `TypeError`.  Removing these code paths seems pretty trivial.
@phyy-nx and I stubbed our toes on this last week when trying to run [`xia2.multiplex`](https://dials.github.io/documentation/programs/xia2_multiplex.html), of which MMTBX is a dependency.
I've no idea why tests are failing in the CI.  They don't, at first glance, seem to be related to these changes.  @bkpoon, could you please advise as to how you would like me to proceed?
=> MMTBX: remove comparison of int with NoneType

xfel/merging/application/input/file_loader.py
This PR removes line `self.params.input.path = None # Rank 0 has already parsed the input parameters` from `xfel/merging/application/input/file_loader.py`. With this change phil parameter `input.path` should be accessible for rank 0 for all downstream workers.
I looked at the code and this change should not affect any existing functionality; however, since theoretically it can indirectly affect all `cctbx.xfel.merge` workers, I am running it via PR to make sure it passes all tests first.
=> Don't `self.params.input.path = None` after `list_input_pairs` on rank0

xfel/merging/application/phil/phil.py, xfel/merging/application/statistics/deltaccint.py, xfel/merging/application/statistics/factory.py
This is a means of filtering out lattices that degrade the overall CC½. Uses the σ-τ method from [Assmann 2016](https://journals.iucr.org/j/issues/2016/03/00/zw5005/#FD4) to avoid splitting the data into odd/even datasets. Enable by adding the deltaccint worker after the group worker.
Includes parameter iqr_ratio = 10. If the ΔCC½ filter is enabled, first compute CC½ when removing every image one at a time, then compute the IQR of these CC½s.  Remove all lattices whose contribution degrades CC½ by more than IQR * iqr_ratio above the median. You can discover a good IQR by running the program once, examining the log file where possible values are listed, and running it again with the best value.
Implementation heavily uses MPI for fast computation of ΔCC½ on thousands of images.  Current …
=> New cctbx.xfel.merge worker for computing and filtering on ΔCC½

libtbx/mpi4py.py, xfel/merging/application/errors/error_modifier_mm24.py, xfel/merging/application/filter/global_filter.py, xfel/merging/application/mpi_helper.py, xfel/merging/application/statistics/beam_statistics.py, xfel/merging/application/statistics/unit_cell_statistics.py
A common pattern in multiprocessing is to collect data on the root (typically rank 0), process it there, and broadcast it back to other ranks. However, the better practice is typically to use a non-rooted operation: pass the inputs between all ranks and perform calculations independently on each. This removes the need for a second communication (broadcast) and improves code readability.
Non-rooted approach is inferior only in these rare cases where the cost of the switching to non-rooted operation is much larger than the cost of the secondary broadcast. Non-rooted approach might potentially also cause issues with memory consumption if the input or temporary objects (created when analyzing input) are very volumous.
In xfel, communicating between ranks can be done using the `mpi_helper` …
=> Make `mpi_helper`'s method non-rooted if `root=None` 

xfel/merging/application/modify/aux_cosym.py
Avoid any additional filtering introduced by https://github.com/dials/dials/pull/2741 in order to preserve current behaviour.
=> Maintain cctbx.xfel.merge cosym behaviour

xfel/command_line/upload_mtz.py
I'm using the `pydrive2_interface` to upload cctbx.xfel installers to Google Drive and Windows does not have `fcntl`. This should just skip the file locking on Windows.
=> xfel: skip fcntl for Windows

mmtbx/model/model.py, mmtbx/programs/probe2.py, mmtbx/programs/reduce2.py
Fixes some bugs in probe2 so that it can load more files, and prints more robust errors when it fails.
Adds the ability to export a JSON format to probe2 with the same data as the raw format but also able to handle CIF files.
=> Probe2 json

.azure-pipelines/xfel/conda-linux.yml, .azure-pipelines/xfel/unix-psana-build.yml, xfel/conda_envs/README.md
Observed some flaky behavior ("Missing hostname or invalid host/port description in business card") with mpirun in Rocky Linux on Azure. Apparently fixed by installing ucx.
=> Fix MPI on XFEL CI for psana

libtbx/auto_build/bootstrap.py
This fix:
1. Removes the `--enable_cxx11` flag
2. Ensures that `--cxxstd=c++14` is set
It follows similar patterns in the `bootstap.py` file. This is necessary to make the `alcc-recipes` deployment on Perlmutter work after the most recent compiler toolchain update (which also replaces the boost install with conda forge's boost).
Before merging, we might want to discuss if this is the best way to implement "a non-ancient c++ standard". E.g.:
1. Do we want to enable even more recent C++ versions? (E.g. let the user specify the C++ standard and just ensure that it's "at least C++14")
2. Do we want to remove the `--enable_cxx11` flag alltogether?
Anyone on Perlmutter, please give https://github.com/JBlaschke/alcc-recipes/blob/master/cctbx/setup_perlmutter_new.sh a try to see if it also works …
=> Don't use cxx11

libtbx/auto_build/bootstrap.py
This is the end of a rabbit hole of dependencies.  I thought I'd write it here in case it comes up again.  Thanks @fredericpoitevin and @nksauter.
- psana is being upgraded to psana2, which can read xtc2, the file format created by lcls2
- We found that the order of imports would cause a failure in a minimal script which connected to a psana2 data source.  This would fail:
```
import rstbx.cftbx
import psana
```
But this would pass
```
import psana
import rstbx.cftbx
```
- The problem was that `cftbx` triggers an import of `rstbx/__init__.py` which includes `omptbx_ext`, the OpenMP adapter in cctbx.  At this point we think we know what happens next.
- `omptbx/omp_or_stubs.h` includes this code:
```
#if defined(_OPENMP)
#else
#endif
```
In other words, if OpenMP is enabled, use `omp.h`, …
=> Add openmp to the XFEL builder by default

.azure-pipelines/xfel/unix-conda-build.yml, .azure-pipelines/xfel/unix-psana-build.yml, libtbx/env_config.py
Legacy-editable mode was removed in pypa/setuptools#4953, this env
variable no longer does anything. We accommodate the new behavior in
cctbx/dxtbx#807 and dials/dials#2906.
=> Stop attempting "legacy editable" installs

xfel/merging/application/filter/reflection_filter.py, xfel/merging/application/phil/phil.py
The isolation forest filter was having an out of memory error. The random forest models were very large. I set the number of estimators to 1,000 initially in development because it gave smooth decision boundaries. I reset this to 100 (sklearn's default). The problem was when the root rank communicated the models to the other ranks, the communication packet was just too large. I also changed from a comm.bcast to sending the model individually to the other ranks. I have found this to help with out of memory issues during mpi communications in the past.
=> Fixed out of memory error in cctbx.xfel.merge's isolation forest filter.

cctbx/miller/__init__.py, cctbx/xray/structure.py, cctbx/xray/structure_factors/__init__.py, cctbx/xray/structure_factors/algorithm.py, cctbx/xray/structure_factors/from_scatterers.py, cctbx/xray/structure_factors/from_scatterers_direct.py, cctbx/xray/structure_factors/from_scatterers_fft.py, cctbx/xray/structure_factors/gradients.py, cctbx/xray/structure_factors/gradients_direct.py, cctbx/xray/structure_factors/gradients_fft.py, cctbx/xray/structure_factors/manager.py, cctbx/xray/structure_factors/misc.py, mmtbx/__init__.py, mmtbx/f_model/f_model.py, mmtbx/refinement/anomalous_scatterer_groups.py, mmtbx/refinement/data.py, mmtbx/refinement/targets.py, mmtbx/refinement/weights.py, mmtbx/twinning/twin_f_model.py, mmtbx/utils/__init__.py
Hello!
This PR aims to make use of the existing structure factor + gradient framework in cctbx when using TAAM with pydiscamb.
I refactored the algorithm selection slightly, and added TAAM as an option. Currently, the actual implementation is in pydiscamb: https://github.com/viljarjf/pyDiSCaMB/blob/main/pydiscamb/cctbx_interface.py
I would like some input on this solution, if maybe the `gradients_taam` and `from_scatterers_taam` classes should be in cctbx and the results classes in pydiscamb?
The runtime measurement still needs to be added to the taam classes, regardless.
Extra parameters can be passed to DiSCaMB by means of a phil scope. I put this in pydiscamb, to more easily support / update the options if and when they change in DiSCaMB. The `extra`-scope is meant to allow for other …
=> Refactor pydiscamb interface

mmtbx/probe/Helpers.py, mmtbx/programs/reduce2.py, mmtbx/reduce/Optimizers.py
Has reduce2 continuing to run with default values for atoms whose hydrogen-bonding status or other characteristics cannot be determined (unknown HET groups). This enables reduce2 to run on a wider range of models with the goal of running on all models in the PDB and corner cases.
Prints all of the warnings on the console and the description output with Warning: prefixed to indicate the problems to the person running it.
=> Reduce2 skip bad atoms
